-- Generated thousands of Bible quiz questions
-- Run this AFTER migrate_quiz_questions.sql
-- This file contains thousands of template-based questions

INSERT INTO quiz_questions (question, options, correct_answer, reference, difficulty, category, book, chapter, question_type)
VALUES
  ('How many verses are typically in Hosea chapter 11?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Hosea 11', 'easy', 'Old Testament', 'Hosea', 11, 'chapter'),
  ('What is the main theme of Hosea chapter 12?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Hosea 12', 'medium', 'Old Testament', 'Hosea', 12, 'chapter'),
  ('How many verses are typically in Hosea chapter 12?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Hosea 12', 'easy', 'Old Testament', 'Hosea', 12, 'chapter'),
  ('What is the main theme of Hosea chapter 13?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Hosea 13', 'medium', 'Old Testament', 'Hosea', 13, 'chapter'),
  ('How many verses are typically in Hosea chapter 13?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Hosea 13', 'easy', 'Old Testament', 'Hosea', 13, 'chapter'),
  ('What is the main theme of Hosea chapter 14?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Hosea 14', 'medium', 'Old Testament', 'Hosea', 14, 'chapter'),
  ('How many verses are typically in Hosea chapter 14?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Hosea 14', 'easy', 'Old Testament', 'Hosea', 14, 'chapter'),
  ('Who is traditionally believed to have written Joel?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Joel', 'medium', 'Old Testament', 'Joel', NULL, 'book'),
  ('How many chapters are in the book of Joel?', '["3","8","13","18"]', '3', 'Joel', 'easy', 'Old Testament', 'Joel', NULL, 'book'),
  ('What testament is Joel in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Joel', 'easy', 'Old Testament', 'Joel', NULL, 'book'),
  ('What is the main theme of Joel chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Joel 1', 'medium', 'Old Testament', 'Joel', 1, 'chapter'),
  ('How many verses are typically in Joel chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Joel 1', 'easy', 'Old Testament', 'Joel', 1, 'chapter'),
  ('What is the main theme of Joel chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Joel 2', 'medium', 'Old Testament', 'Joel', 2, 'chapter'),
  ('How many verses are typically in Joel chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Joel 2', 'easy', 'Old Testament', 'Joel', 2, 'chapter'),
  ('What is the main theme of Joel chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Joel 3', 'medium', 'Old Testament', 'Joel', 3, 'chapter'),
  ('How many verses are typically in Joel chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Joel 3', 'easy', 'Old Testament', 'Joel', 3, 'chapter'),
  ('Who is traditionally believed to have written Amos?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Amos', 'medium', 'Old Testament', 'Amos', NULL, 'book'),
  ('How many chapters are in the book of Amos?', '["9","14","19","24"]', '9', 'Amos', 'easy', 'Old Testament', 'Amos', NULL, 'book'),
  ('What testament is Amos in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Amos', 'easy', 'Old Testament', 'Amos', NULL, 'book'),
  ('What is the main theme of Amos chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 1', 'medium', 'Old Testament', 'Amos', 1, 'chapter'),
  ('How many verses are typically in Amos chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 1', 'easy', 'Old Testament', 'Amos', 1, 'chapter'),
  ('What is the main theme of Amos chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 2', 'medium', 'Old Testament', 'Amos', 2, 'chapter'),
  ('How many verses are typically in Amos chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 2', 'easy', 'Old Testament', 'Amos', 2, 'chapter'),
  ('What is the main theme of Amos chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 3', 'medium', 'Old Testament', 'Amos', 3, 'chapter'),
  ('How many verses are typically in Amos chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 3', 'easy', 'Old Testament', 'Amos', 3, 'chapter'),
  ('What is the main theme of Amos chapter 4?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 4', 'medium', 'Old Testament', 'Amos', 4, 'chapter'),
  ('How many verses are typically in Amos chapter 4?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 4', 'easy', 'Old Testament', 'Amos', 4, 'chapter'),
  ('What is the main theme of Amos chapter 5?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 5', 'medium', 'Old Testament', 'Amos', 5, 'chapter'),
  ('How many verses are typically in Amos chapter 5?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 5', 'easy', 'Old Testament', 'Amos', 5, 'chapter'),
  ('What is the main theme of Amos chapter 6?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 6', 'medium', 'Old Testament', 'Amos', 6, 'chapter'),
  ('How many verses are typically in Amos chapter 6?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 6', 'easy', 'Old Testament', 'Amos', 6, 'chapter'),
  ('What is the main theme of Amos chapter 7?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 7', 'medium', 'Old Testament', 'Amos', 7, 'chapter'),
  ('How many verses are typically in Amos chapter 7?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 7', 'easy', 'Old Testament', 'Amos', 7, 'chapter'),
  ('What is the main theme of Amos chapter 8?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 8', 'medium', 'Old Testament', 'Amos', 8, 'chapter'),
  ('How many verses are typically in Amos chapter 8?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 8', 'easy', 'Old Testament', 'Amos', 8, 'chapter'),
  ('What is the main theme of Amos chapter 9?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Amos 9', 'medium', 'Old Testament', 'Amos', 9, 'chapter'),
  ('How many verses are typically in Amos chapter 9?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Amos 9', 'easy', 'Old Testament', 'Amos', 9, 'chapter'),
  ('Who is traditionally believed to have written Obadiah?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Obadiah', 'medium', 'Old Testament', 'Obadiah', NULL, 'book'),
  ('How many chapters are in the book of Obadiah?', '["1","6","11","16"]', '1', 'Obadiah', 'easy', 'Old Testament', 'Obadiah', NULL, 'book'),
  ('What testament is Obadiah in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Obadiah', 'easy', 'Old Testament', 'Obadiah', NULL, 'book'),
  ('What is the main theme of Obadiah chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Obadiah 1', 'medium', 'Old Testament', 'Obadiah', 1, 'chapter'),
  ('How many verses are typically in Obadiah chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Obadiah 1', 'easy', 'Old Testament', 'Obadiah', 1, 'chapter'),
  ('Who is traditionally believed to have written Jonah?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Jonah', 'medium', 'Old Testament', 'Jonah', NULL, 'book'),
  ('How many chapters are in the book of Jonah?', '["4","9","14","19"]', '4', 'Jonah', 'easy', 'Old Testament', 'Jonah', NULL, 'book'),
  ('What testament is Jonah in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Jonah', 'easy', 'Old Testament', 'Jonah', NULL, 'book'),
  ('What is the main theme of Jonah chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Jonah 1', 'medium', 'Old Testament', 'Jonah', 1, 'chapter'),
  ('How many verses are typically in Jonah chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Jonah 1', 'easy', 'Old Testament', 'Jonah', 1, 'chapter'),
  ('What is the main theme of Jonah chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Jonah 2', 'medium', 'Old Testament', 'Jonah', 2, 'chapter'),
  ('How many verses are typically in Jonah chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Jonah 2', 'easy', 'Old Testament', 'Jonah', 2, 'chapter'),
  ('What is the main theme of Jonah chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Jonah 3', 'medium', 'Old Testament', 'Jonah', 3, 'chapter'),
  ('How many verses are typically in Jonah chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Jonah 3', 'easy', 'Old Testament', 'Jonah', 3, 'chapter'),
  ('What is the main theme of Jonah chapter 4?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Jonah 4', 'medium', 'Old Testament', 'Jonah', 4, 'chapter'),
  ('How many verses are typically in Jonah chapter 4?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Jonah 4', 'easy', 'Old Testament', 'Jonah', 4, 'chapter'),
  ('Who is traditionally believed to have written Micah?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Micah', 'medium', 'Old Testament', 'Micah', NULL, 'book'),
  ('How many chapters are in the book of Micah?', '["7","12","17","22"]', '7', 'Micah', 'easy', 'Old Testament', 'Micah', NULL, 'book'),
  ('What testament is Micah in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Micah', 'easy', 'Old Testament', 'Micah', NULL, 'book'),
  ('What is the main theme of Micah chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 1', 'medium', 'Old Testament', 'Micah', 1, 'chapter'),
  ('How many verses are typically in Micah chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 1', 'easy', 'Old Testament', 'Micah', 1, 'chapter'),
  ('What is the main theme of Micah chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 2', 'medium', 'Old Testament', 'Micah', 2, 'chapter'),
  ('How many verses are typically in Micah chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 2', 'easy', 'Old Testament', 'Micah', 2, 'chapter'),
  ('What is the main theme of Micah chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 3', 'medium', 'Old Testament', 'Micah', 3, 'chapter'),
  ('How many verses are typically in Micah chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 3', 'easy', 'Old Testament', 'Micah', 3, 'chapter'),
  ('What is the main theme of Micah chapter 4?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 4', 'medium', 'Old Testament', 'Micah', 4, 'chapter'),
  ('How many verses are typically in Micah chapter 4?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 4', 'easy', 'Old Testament', 'Micah', 4, 'chapter'),
  ('What is the main theme of Micah chapter 5?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 5', 'medium', 'Old Testament', 'Micah', 5, 'chapter'),
  ('How many verses are typically in Micah chapter 5?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 5', 'easy', 'Old Testament', 'Micah', 5, 'chapter'),
  ('What is the main theme of Micah chapter 6?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 6', 'medium', 'Old Testament', 'Micah', 6, 'chapter'),
  ('How many verses are typically in Micah chapter 6?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 6', 'easy', 'Old Testament', 'Micah', 6, 'chapter'),
  ('What is the main theme of Micah chapter 7?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Micah 7', 'medium', 'Old Testament', 'Micah', 7, 'chapter'),
  ('How many verses are typically in Micah chapter 7?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Micah 7', 'easy', 'Old Testament', 'Micah', 7, 'chapter'),
  ('Who is traditionally believed to have written Nahum?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Nahum', 'medium', 'Old Testament', 'Nahum', NULL, 'book'),
  ('How many chapters are in the book of Nahum?', '["3","8","13","18"]', '3', 'Nahum', 'easy', 'Old Testament', 'Nahum', NULL, 'book'),
  ('What testament is Nahum in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Nahum', 'easy', 'Old Testament', 'Nahum', NULL, 'book'),
  ('What is the main theme of Nahum chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Nahum 1', 'medium', 'Old Testament', 'Nahum', 1, 'chapter'),
  ('How many verses are typically in Nahum chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Nahum 1', 'easy', 'Old Testament', 'Nahum', 1, 'chapter'),
  ('What is the main theme of Nahum chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Nahum 2', 'medium', 'Old Testament', 'Nahum', 2, 'chapter'),
  ('How many verses are typically in Nahum chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Nahum 2', 'easy', 'Old Testament', 'Nahum', 2, 'chapter'),
  ('What is the main theme of Nahum chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Nahum 3', 'medium', 'Old Testament', 'Nahum', 3, 'chapter'),
  ('How many verses are typically in Nahum chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Nahum 3', 'easy', 'Old Testament', 'Nahum', 3, 'chapter'),
  ('Who is traditionally believed to have written Habakkuk?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Habakkuk', 'medium', 'Old Testament', 'Habakkuk', NULL, 'book'),
  ('How many chapters are in the book of Habakkuk?', '["3","8","13","18"]', '3', 'Habakkuk', 'easy', 'Old Testament', 'Habakkuk', NULL, 'book'),
  ('What testament is Habakkuk in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Habakkuk', 'easy', 'Old Testament', 'Habakkuk', NULL, 'book'),
  ('What is the main theme of Habakkuk chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Habakkuk 1', 'medium', 'Old Testament', 'Habakkuk', 1, 'chapter'),
  ('How many verses are typically in Habakkuk chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Habakkuk 1', 'easy', 'Old Testament', 'Habakkuk', 1, 'chapter'),
  ('What is the main theme of Habakkuk chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Habakkuk 2', 'medium', 'Old Testament', 'Habakkuk', 2, 'chapter'),
  ('How many verses are typically in Habakkuk chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Habakkuk 2', 'easy', 'Old Testament', 'Habakkuk', 2, 'chapter'),
  ('What is the main theme of Habakkuk chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Habakkuk 3', 'medium', 'Old Testament', 'Habakkuk', 3, 'chapter'),
  ('How many verses are typically in Habakkuk chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Habakkuk 3', 'easy', 'Old Testament', 'Habakkuk', 3, 'chapter'),
  ('Who is traditionally believed to have written Zephaniah?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Zephaniah', 'medium', 'Old Testament', 'Zephaniah', NULL, 'book'),
  ('How many chapters are in the book of Zephaniah?', '["3","8","13","18"]', '3', 'Zephaniah', 'easy', 'Old Testament', 'Zephaniah', NULL, 'book'),
  ('What testament is Zephaniah in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Zephaniah', 'easy', 'Old Testament', 'Zephaniah', NULL, 'book'),
  ('What is the main theme of Zephaniah chapter 1?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Zephaniah 1', 'medium', 'Old Testament', 'Zephaniah', 1, 'chapter'),
  ('How many verses are typically in Zephaniah chapter 1?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Zephaniah 1', 'easy', 'Old Testament', 'Zephaniah', 1, 'chapter'),
  ('What is the main theme of Zephaniah chapter 2?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Zephaniah 2', 'medium', 'Old Testament', 'Zephaniah', 2, 'chapter'),
  ('How many verses are typically in Zephaniah chapter 2?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Zephaniah 2', 'easy', 'Old Testament', 'Zephaniah', 2, 'chapter'),
  ('What is the main theme of Zephaniah chapter 3?', '["God''s love and grace","Faith and obedience","Wisdom and understanding","Salvation and redemption"]', 'Faith and obedience', 'Zephaniah 3', 'medium', 'Old Testament', 'Zephaniah', 3, 'chapter'),
  ('How many verses are typically in Zephaniah chapter 3?', '["10-20 verses","20-30 verses","30-40 verses","40+ verses"]', '20-30 verses', 'Zephaniah 3', 'easy', 'Old Testament', 'Zephaniah', 3, 'chapter'),
  ('Who is traditionally believed to have written Haggai?', '["Unknown","Moses","David","Paul"]', 'Unknown', 'Haggai', 'medium', 'Old Testament', 'Haggai', NULL, 'book'),
  ('How many chapters are in the book of Haggai?', '["2","7","12","17"]', '2', 'Haggai', 'easy', 'Old Testament', 'Haggai', NULL, 'book'),
  ('What testament is Haggai in?', '["Old Testament","New Testament","Both","Neither"]', 'Old Testament', 'Haggai', 'easy', 'Old Testament', 'Haggai', NULL, 'book');

-- Batch 22 of 30 (100 questions)