import theme from './theme';

// Additional 100+ Reading Plans - Batch 2
// Continuing to build comprehensive library

export const EXTENDED_READING_PLANS_2 = [
  // ===== OLD TESTAMENT BOOKS (50+ plans) =====
  {
    id: 69,
    plan_type: 'genesis_beginnings',
    title: 'Genesis - Beginnings',
    description: 'In the beginning God created',
    category: 'Old Testament',
    total_days: 50,
    icon: 'planet',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 50 }, (_, i) => ({
      book: 'Genesis',
      chapter: i + 1,
      verses: '1-46',
      title: `Genesis ${i + 1}`
    })),
  },
  {
    id: 70,
    plan_type: 'exodus_freedom',
    title: 'Exodus - Journey to Freedom',
    description: 'Let my people go',
    category: 'Old Testament',
    total_days: 40,
    icon: 'walk',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 40 }, (_, i) => ({
      book: 'Exodus',
      chapter: i + 1,
      verses: '1-40',
      title: `Exodus ${i + 1}`
    })),
  },
  {
    id: 71,
    plan_type: 'leviticus_holiness',
    title: 'Leviticus - Be Holy',
    description: 'Laws of holiness',
    category: 'Old Testament',
    total_days: 27,
    icon: 'flame',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 27 }, (_, i) => ({
      book: 'Leviticus',
      chapter: i + 1,
      verses: '1-34',
      title: `Leviticus ${i + 1}`
    })),
  },
  {
    id: 72,
    plan_type: 'numbers_wilderness',
    title: 'Numbers - Wilderness Journey',
    description: 'Wandering and learning',
    category: 'Old Testament',
    total_days: 36,
    icon: 'navigate',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 36 }, (_, i) => ({
      book: 'Numbers',
      chapter: i + 1,
      verses: '1-54',
      title: `Numbers ${i + 1}`
    })),
  },
  {
    id: 73,
    plan_type: 'deuteronomy_covenant',
    title: 'Deuteronomy - Covenant Renewed',
    description: 'Choose life',
    category: 'Old Testament',
    total_days: 34,
    icon: 'document',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 34 }, (_, i) => ({
      book: 'Deuteronomy',
      chapter: i + 1,
      verses: '1-68',
      title: `Deuteronomy ${i + 1}`
    })),
  },
  {
    id: 74,
    plan_type: 'joshua_promised_land',
    title: 'Joshua - Taking the Land',
    description: 'Be strong and courageous',
    category: 'Old Testament',
    total_days: 24,
    icon: 'flag',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 24 }, (_, i) => ({
      book: 'Joshua',
      chapter: i + 1,
      verses: '1-51',
      title: `Joshua ${i + 1}`
    })),
  },
  {
    id: 75,
    plan_type: 'judges_cycle',
    title: 'Judges - Cycle of Rebellion',
    description: 'Everyone did what was right',
    category: 'Old Testament',
    total_days: 21,
    icon: 'repeat',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 21 }, (_, i) => ({
      book: 'Judges',
      chapter: i + 1,
      verses: '1-36',
      title: `Judges ${i + 1}`
    })),
  },
  {
    id: 76,
    plan_type: 'ruth_loyalty',
    title: 'Ruth - Loyal Love',
    description: 'Where you go I will go',
    category: 'Old Testament',
    total_days: 4,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: Array.from({ length: 4 }, (_, i) => ({
      book: 'Ruth',
      chapter: i + 1,
      verses: '1-22',
      title: `Ruth ${i + 1}`
    })),
  },
  {
    id: 77,
    plan_type: 'first_samuel',
    title: '1 Samuel - Rise of Kings',
    description: 'From judges to kings',
    category: 'Old Testament',
    total_days: 31,
    icon: 'ribbon',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 31 }, (_, i) => ({
      book: '1 Samuel',
      chapter: i + 1,
      verses: '1-58',
      title: `1 Samuel ${i + 1}`
    })),
  },
  {
    id: 78,
    plan_type: 'second_samuel',
    title: '2 Samuel - David\'s Reign',
    description: 'A man after God\'s heart',
    category: 'Old Testament',
    total_days: 24,
    icon: 'star',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 24 }, (_, i) => ({
      book: '2 Samuel',
      chapter: i + 1,
      verses: '1-51',
      title: `2 Samuel ${i + 1}`
    })),
  },
  {
    id: 79,
    plan_type: 'first_kings',
    title: '1 Kings - Divided Kingdom',
    description: 'Solomon and the split',
    category: 'Old Testament',
    total_days: 22,
    icon: 'albums',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 22 }, (_, i) => ({
      book: '1 Kings',
      chapter: i + 1,
      verses: '1-66',
      title: `1 Kings ${i + 1}`
    })),
  },
  {
    id: 80,
    plan_type: 'second_kings',
    title: '2 Kings - Fall of Nations',
    description: 'Israel and Judah fall',
    category: 'Old Testament',
    total_days: 25,
    icon: 'trending-down',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 25 }, (_, i) => ({
      book: '2 Kings',
      chapter: i + 1,
      verses: '1-37',
      title: `2 Kings ${i + 1}`
    })),
  },
  {
    id: 81,
    plan_type: 'first_chronicles',
    title: '1 Chronicles - David\'s Legacy',
    description: 'Genealogies and David',
    category: 'Old Testament',
    total_days: 29,
    icon: 'list',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 29 }, (_, i) => ({
      book: '1 Chronicles',
      chapter: i + 1,
      verses: '1-80',
      title: `1 Chronicles ${i + 1}`
    })),
  },
  {
    id: 82,
    plan_type: 'second_chronicles',
    title: '2 Chronicles - Temple History',
    description: 'From Solomon to exile',
    category: 'Old Testament',
    total_days: 36,
    icon: 'business',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 36 }, (_, i) => ({
      book: '2 Chronicles',
      chapter: i + 1,
      verses: '1-42',
      title: `2 Chronicles ${i + 1}`
    })),
  },
  {
    id: 83,
    plan_type: 'ezra_return',
    title: 'Ezra - The Return',
    description: 'Rebuilding the temple',
    category: 'Old Testament',
    total_days: 10,
    icon: 'construct',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 10 }, (_, i) => ({
      book: 'Ezra',
      chapter: i + 1,
      verses: '1-70',
      title: `Ezra ${i + 1}`
    })),
  },
  {
    id: 84,
    plan_type: 'nehemiah_walls',
    title: 'Nehemiah - Rebuilding Walls',
    description: 'The work of rebuilding',
    category: 'Old Testament',
    total_days: 13,
    icon: 'construct',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 13 }, (_, i) => ({
      book: 'Nehemiah',
      chapter: i + 1,
      verses: '1-73',
      title: `Nehemiah ${i + 1}`
    })),
  },
  {
    id: 85,
    plan_type: 'esther_deliverance',
    title: 'Esther - For Such a Time',
    description: 'Courage and deliverance',
    category: 'Old Testament',
    total_days: 10,
    icon: 'star',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 10 }, (_, i) => ({
      book: 'Esther',
      chapter: i + 1,
      verses: '1-32',
      title: `Esther ${i + 1}`
    })),
  },
  {
    id: 86,
    plan_type: 'job_suffering',
    title: 'Job - Suffering & Sovereignty',
    description: 'Though He slay me',
    category: 'Wisdom',
    total_days: 42,
    icon: 'help-circle',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 42 }, (_, i) => ({
      book: 'Job',
      chapter: i + 1,
      verses: '1-34',
      title: `Job ${i + 1}`
    })),
  },
  {
    id: 87,
    plan_type: 'ecclesiastes_meaning',
    title: 'Ecclesiastes - Under the Sun',
    description: 'Meaning and purpose',
    category: 'Wisdom',
    total_days: 12,
    icon: 'sunny',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 12 }, (_, i) => ({
      book: 'Ecclesiastes',
      chapter: i + 1,
      verses: '1-20',
      title: `Ecclesiastes ${i + 1}`
    })),
  },
  {
    id: 88,
    plan_type: 'song_of_solomon_love',
    title: 'Song of Songs - Divine Love',
    description: 'Love songs',
    category: 'Wisdom',
    total_days: 8,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: Array.from({ length: 8 }, (_, i) => ({
      book: 'Song of Solomon',
      chapter: i + 1,
      verses: '1-17',
      title: `Song of Songs ${i + 1}`
    })),
  },

  // ===== TOPICAL - CHARACTER STUDIES (20 plans) =====
  {
    id: 89,
    plan_type: 'abraham_faith',
    title: 'Abraham - Father of Faith',
    description: 'Called to go out',
    category: 'Character Studies',
    total_days: 10,
    icon: 'person',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Genesis', chapter: 12, verses: '1-9', title: 'The Call' },
      { book: 'Genesis', chapter: 15, verses: '1-21', title: 'The Covenant' },
      { book: 'Genesis', chapter: 17, verses: '1-27', title: 'Abraham and Circumcision' },
      { book: 'Genesis', chapter: 18, verses: '1-33', title: 'Three Visitors' },
      { book: 'Genesis', chapter: 22, verses: '1-19', title: 'Sacrifice of Isaac' },
      { book: 'Romans', chapter: 4, verses: '1-25', title: 'Justified by Faith' },
      { book: 'Hebrews', chapter: 11, verses: '8-19', title: 'By Faith Abraham' },
      { book: 'James', chapter: 2, verses: '20-24', title: 'Faith and Works' },
      { book: 'Galatians', chapter: 3, verses: '6-9', title: 'Children of Abraham' },
      { book: 'Genesis', chapter: 25, verses: '7-11', title: 'Abraham\'s Death' },
    ],
  },
  {
    id: 90,
    plan_type: 'moses_leader',
    title: 'Moses - Reluctant Leader',
    description: 'The man who spoke with God',
    category: 'Character Studies',
    total_days: 12,
    icon: 'person',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Exodus', chapter: 2, verses: '1-25', title: 'Birth and Flight' },
      { book: 'Exodus', chapter: 3, verses: '1-22', title: 'Burning Bush' },
      { book: 'Exodus', chapter: 4, verses: '1-31', title: 'Signs and Objections' },
      { book: 'Exodus', chapter: 14, verses: '10-31', title: 'Red Sea' },
      { book: 'Exodus', chapter: 19, verses: '1-25', title: 'Mount Sinai' },
      { book: 'Exodus', chapter: 32, verses: '1-35', title: 'Golden Calf' },
      { book: 'Exodus', chapter: 33, verses: '7-23', title: 'Face to Face' },
      { book: 'Exodus', chapter: 34, verses: '1-35', title: 'New Tablets' },
      { book: 'Numbers', chapter: 20, verses: '1-13', title: 'Moses\' Mistake' },
      { book: 'Deuteronomy', chapter: 34, verses: '1-12', title: 'Death of Moses' },
      { book: 'Hebrews', chapter: 11, verses: '23-29', title: 'By Faith Moses' },
      { book: 'Jude', chapter: 1, verses: '9', title: 'Dispute over Body' },
    ],
  },
  {
    id: 91,
    plan_type: 'joseph_dreamer',
    title: 'Joseph - The Dreamer',
    description: 'From pit to palace',
    category: 'Character Studies',
    total_days: 12,
    icon: 'star',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Genesis', chapter: 37, verses: '1-36', title: 'Joseph\'s Dreams' },
      { book: 'Genesis', chapter: 39, verses: '1-23', title: 'Potiphar\'s House' },
      { book: 'Genesis', chapter: 40, verses: '1-23', title: 'Interpreting Dreams' },
      { book: 'Genesis', chapter: 41, verses: '1-57', title: 'Before Pharaoh' },
      { book: 'Genesis', chapter: 42, verses: '1-38', title: 'Brothers Come to Egypt' },
      { book: 'Genesis', chapter: 43, verses: '1-34', title: 'Second Journey' },
      { book: 'Genesis', chapter: 44, verses: '1-34', title: 'The Silver Cup' },
      { book: 'Genesis', chapter: 45, verses: '1-28', title: 'Joseph Reveals Himself' },
      { book: 'Genesis', chapter: 46, verses: '1-34', title: 'Jacob to Egypt' },
      { book: 'Genesis', chapter: 47, verses: '1-31', title: 'Settled in Goshen' },
      { book: 'Genesis', chapter: 50, verses: '15-26', title: 'Meant for Good' },
      { book: 'Hebrews', chapter: 11, verses: '22', title: 'By Faith Joseph' },
    ],
  },
  {
    id: 92,
    plan_type: 'elijah_prophet',
    title: 'Elijah - Fire from Heaven',
    description: 'Bold prophet of God',
    category: 'Character Studies',
    total_days: 10,
    icon: 'flame',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: '1 Kings', chapter: 17, verses: '1-24', title: 'Drought and Ravens' },
      { book: '1 Kings', chapter: 18, verses: '1-46', title: 'Mount Carmel' },
      { book: '1 Kings', chapter: 19, verses: '1-21', title: 'Still Small Voice' },
      { book: '1 Kings', chapter: 21, verses: '1-29', title: 'Naboth\'s Vineyard' },
      { book: '2 Kings', chapter: 1, verses: '1-18', title: 'Fire from Heaven' },
      { book: '2 Kings', chapter: 2, verses: '1-18', title: 'Taken Up' },
      { book: 'Malachi', chapter: 4, verses: '5-6', title: 'Elijah Will Come' },
      { book: 'Matthew', chapter: 17, verses: '1-13', title: 'Transfiguration' },
      { book: 'Luke', chapter: 1, verses: '13-17', title: 'Spirit of Elijah' },
      { book: 'James', chapter: 5, verses: '17-18', title: 'Elijah\'s Prayer' },
    ],
  },
  {
    id: 93,
    plan_type: 'esther_courage',
    title: 'Esther - Courageous Queen',
    description: 'For such a time as this',
    category: 'Character Studies',
    total_days: 10,
    icon: 'woman',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 10 }, (_, i) => ({
      book: 'Esther',
      chapter: i + 1,
      verses: '1-32',
      title: `Esther ${i + 1}`
    })),
  },
  {
    id: 94,
    plan_type: 'peter_rock',
    title: 'Peter - From Fisherman to Rock',
    description: 'Transformation of a disciple',
    category: 'Character Studies',
    total_days: 10,
    icon: 'person',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Matthew', chapter: 4, verses: '18-22', title: 'Called to Follow' },
      { book: 'Matthew', chapter: 14, verses: '22-33', title: 'Walking on Water' },
      { book: 'Matthew', chapter: 16, verses: '13-20', title: 'You Are the Christ' },
      { book: 'Matthew', chapter: 26, verses: '31-35', title: 'Will Never Disown' },
      { book: 'John', chapter: 18, verses: '15-27', title: 'Denial' },
      { book: 'John', chapter: 21, verses: '15-19', title: 'Do You Love Me' },
      { book: 'Acts', chapter: 2, verses: '14-41', title: 'Pentecost Sermon' },
      { book: 'Acts', chapter: 3, verses: '1-26', title: 'Healing at the Gate' },
      { book: 'Acts', chapter: 10, verses: '1-48', title: 'Vision and Cornelius' },
      { book: 'Galatians', chapter: 2, verses: '11-21', title: 'Confronted by Paul' },
    ],
  },
  {
    id: 95,
    plan_type: 'mary_mother',
    title: 'Mary - Mother of Jesus',
    description: 'Blessed among women',
    category: 'Character Studies',
    total_days: 7,
    icon: 'woman',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Luke', chapter: 1, verses: '26-38', title: 'The Annunciation' },
      { book: 'Luke', chapter: 1, verses: '39-56', title: 'Mary\'s Song' },
      { book: 'Luke', chapter: 2, verses: '1-20', title: 'Birth of Jesus' },
      { book: 'Luke', chapter: 2, verses: '41-52', title: 'Boy Jesus at Temple' },
      { book: 'John', chapter: 2, verses: '1-11', title: 'Wedding at Cana' },
      { book: 'John', chapter: 19, verses: '25-27', title: 'At the Cross' },
      { book: 'Acts', chapter: 1, verses: '12-14', title: 'In the Upper Room' },
    ],
  },
  {
    id: 96,
    plan_type: 'john_beloved',
    title: 'John - The Beloved Disciple',
    description: 'The disciple Jesus loved',
    category: 'Character Studies',
    total_days: 8,
    icon: 'person',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Mark', chapter: 1, verses: '16-20', title: 'Called to Follow' },
      { book: 'Mark', chapter: 9, verses: '2-13', title: 'Transfiguration' },
      { book: 'Luke', chapter: 9, verses: '51-56', title: 'Fire from Heaven?' },
      { book: 'John', chapter: 13, verses: '21-25', title: 'Leaning on Jesus' },
      { book: 'John', chapter: 19, verses: '25-27', title: 'Given a Mother' },
      { book: 'John', chapter: 20, verses: '1-10', title: 'Running to the Tomb' },
      { book: 'John', chapter: 21, verses: '20-25', title: 'What About Him?' },
      { book: 'Revelation', chapter: 1, verses: '9-20', title: 'Vision on Patmos' },
    ],
  },
  {
    id: 97,
    plan_type: 'timothy_mentored',
    title: 'Timothy - Paul\'s Protégé',
    description: 'Young leader',
    category: 'Character Studies',
    total_days: 5,
    icon: 'person',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Acts', chapter: 16, verses: '1-5', title: 'Joins Paul' },
      { book: '1 Corinthians', chapter: 4, verses: '14-17', title: 'Sent to Corinth' },
      { book: 'Philippians', chapter: 2, verses: '19-24', title: 'Genuine Concern' },
      { book: '1 Timothy', chapter: 1, verses: '1-20', title: 'Instructions' },
      { book: '2 Timothy', chapter: 1, verses: '1-18', title: 'Fan Into Flame' },
    ],
  },

  // ===== TOPICAL - SPIRITUAL DISCIPLINES (15 plans) =====
  {
    id: 98,
    plan_type: 'fasting_guide',
    title: 'Biblical Fasting',
    description: 'When you fast...',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'nutrition',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Matthew', chapter: 6, verses: '16-18', title: 'When You Fast' },
      { book: 'Isaiah', chapter: 58, verses: '3-12', title: 'True Fasting' },
      { book: 'Joel', chapter: 2, verses: '12-17', title: 'Return to Me' },
      { book: 'Esther', chapter: 4, verses: '15-17', title: 'Esther\'s Fast' },
      { book: 'Daniel', chapter: 10, verses: '2-14', title: 'Daniel\'s Fast' },
      { book: 'Acts', chapter: 13, verses: '2-3', title: 'Worship and Fast' },
      { book: 'Acts', chapter: 14, verses: '21-23', title: 'Prayer and Fasting' },
    ],
  },
  {
    id: 99,
    plan_type: 'solitude_silence',
    title: 'Solitude & Silence',
    description: 'Be still and know',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'leaf',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Psalm', chapter: 46, verses: '10', title: 'Be Still' },
      { book: 'Mark', chapter: 1, verses: '35-39', title: 'Jesus Withdrew' },
      { book: 'Luke', chapter: 5, verses: '16', title: 'Often Withdrew' },
      { book: '1 Kings', chapter: 19, verses: '11-13', title: 'Still Small Voice' },
      { book: 'Matthew', chapter: 14, verses: '23', title: 'Alone to Pray' },
      { book: 'Habakkuk', chapter: 2, verses: '20', title: 'Silent Before Him' },
      { book: 'Lamentations', chapter: 3, verses: '26-28', title: 'Wait Quietly' },
    ],
  },
  {
    id: 100,
    plan_type: 'meditation_scripture',
    title: 'Scripture Meditation',
    description: 'Meditate day and night',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'book',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Joshua', chapter: 1, verses: '8', title: 'Book of the Law' },
      { book: 'Psalm', chapter: 1, verses: '1-6', title: 'Blessed is the One' },
      { book: 'Psalm', chapter: 19, verses: '7-14', title: 'Law of the Lord' },
      { book: 'Psalm', chapter: 119, verses: '9-16', title: 'Hidden in My Heart' },
      { book: 'Psalm', chapter: 119, verses: '97-104', title: 'Oh How I Love' },
      { book: 'Colossians', chapter: 3, verses: '16', title: 'Dwell Richly' },
      { book: '2 Timothy', chapter: 3, verses: '16-17', title: 'God-Breathed' },
    ],
  },
  {
    id: 101,
    plan_type: 'corporate_worship',
    title: 'Gathered Worship',
    description: 'When we come together',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'people',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Hebrews', chapter: 10, verses: '23-25', title: 'Not Forsaking' },
      { book: 'Psalm', chapter: 95, verses: '1-7', title: 'Come Let Us Sing' },
      { book: 'Psalm', chapter: 100, verses: '1-5', title: 'Enter His Gates' },
      { book: 'Psalm', chapter: 122, verses: '1', title: 'House of the Lord' },
      { book: '1 Corinthians', chapter: 14, verses: '26-40', title: 'Order in Worship' },
      { book: 'Ephesians', chapter: 5, verses: '18-21', title: 'Sing and Make Music' },
      { book: 'Colossians', chapter: 3, verses: '16-17', title: 'Teach and Admonish' },
    ],
  },
  {
    id: 102,
    plan_type: 'sabbath_rest',
    title: 'Sabbath Rest',
    description: 'Remember the Sabbath',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'bed',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Genesis', chapter: 2, verses: '1-3', title: 'God Rested' },
      { book: 'Exodus', chapter: 20, verses: '8-11', title: 'Remember the Sabbath' },
      { book: 'Deuteronomy', chapter: 5, verses: '12-15', title: 'Observe the Sabbath' },
      { book: 'Mark', chapter: 2, verses: '23-28', title: 'Lord of the Sabbath' },
      { book: 'Hebrews', chapter: 4, verses: '1-11', title: 'Sabbath Rest Remains' },
      { book: 'Isaiah', chapter: 58, verses: '13-14', title: 'Delight in the Lord' },
      { book: 'Psalm', chapter: 92, verses: '1-15', title: 'Song for the Sabbath' },
    ],
  },
  {
    id: 103,
    plan_type: 'confession_repentance',
    title: 'Confession & Repentance',
    description: 'If we confess our sins',
    category: 'Spiritual Disciplines',
    total_days: 7,
    icon: 'heart-circle',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: '1 John', chapter: 1, verses: '8-10', title: 'If We Confess' },
      { book: 'Psalm', chapter: 51, verses: '1-19', title: 'Have Mercy' },
      { book: 'Psalm', chapter: 32, verses: '1-11', title: 'Blessed is Forgiven' },
      { book: 'Proverbs', chapter: 28, verses: '13', title: 'Confess and Forsake' },
      { book: 'James', chapter: 5, verses: '16', title: 'Confess to Each Other' },
      { book: 'Luke', chapter: 15, verses: '11-32', title: 'Prodigal Son' },
      { book: '2 Chronicles', chapter: 7, verses: '14', title: 'Humble and Pray' },
    ],
  },
];

// Total plans in this batch
export const TOTAL_EXTENDED_PLANS_2 = EXTENDED_READING_PLANS_2.length;

