import theme from './theme';

// Comprehensive Reading Plans Data
// Each plan includes metadata and daily verse references

export const READING_PLANS = [
  // ===== GOSPEL STUDIES =====
  {
    id: 1,
    plan_type: 'gospel_of_john',
    title: 'Gospel of John',
    description: 'Explore the life and teachings of Jesus',
    category: 'Gospels',
    total_days: 21,
    icon: 'book',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'John', chapter: 1, verses: '1-18', title: 'The Word Became Flesh' },
      { book: 'John', chapter: 1, verses: '19-51', title: 'John the Baptist' },
      { book: 'John', chapter: 2, verses: '1-25', title: 'The Wedding at Cana' },
      { book: 'John', chapter: 3, verses: '1-21', title: 'Jesus and Nicodemus' },
      { book: 'John', chapter: 3, verses: '22-36', title: 'John Testifies' },
      { book: 'John', chapter: 4, verses: '1-42', title: 'Woman at the Well' },
      { book: 'John', chapter: 5, verses: '1-30', title: 'Healing on the Sabbath' },
      { book: 'John', chapter: 6, verses: '1-21', title: 'Feeding the 5000' },
      { book: 'John', chapter: 6, verses: '22-59', title: 'Bread of Life' },
      { book: 'John', chapter: 8, verses: '1-30', title: 'Light of the World' },
      { book: 'John', chapter: 10, verses: '1-21', title: 'The Good Shepherd' },
      { book: 'John', chapter: 11, verses: '1-44', title: 'Raising Lazarus' },
      { book: 'John', chapter: 13, verses: '1-20', title: 'Washing Feet' },
      { book: 'John', chapter: 14, verses: '1-14', title: 'The Way, Truth, Life' },
      { book: 'John', chapter: 15, verses: '1-17', title: 'The True Vine' },
      { book: 'John', chapter: 17, verses: '1-26', title: 'High Priestly Prayer' },
      { book: 'John', chapter: 18, verses: '1-27', title: 'Arrest and Trial' },
      { book: 'John', chapter: 19, verses: '1-27', title: 'Crucifixion' },
      { book: 'John', chapter: 19, verses: '28-42', title: 'Death and Burial' },
      { book: 'John', chapter: 20, verses: '1-18', title: 'Empty Tomb' },
      { book: 'John', chapter: 21, verses: '1-25', title: 'Breakfast with Jesus' },
    ],
  },
  {
    id: 2,
    plan_type: 'gospel_of_matthew',
    title: 'Gospel of Matthew',
    description: 'The King and His Kingdom',
    category: 'Gospels',
    total_days: 28,
    icon: 'book',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Matthew', chapter: 1, verses: '1-25', title: 'Birth of Jesus' },
      { book: 'Matthew', chapter: 3, verses: '1-17', title: 'John the Baptist' },
      { book: 'Matthew', chapter: 4, verses: '1-25', title: 'Temptation' },
      { book: 'Matthew', chapter: 5, verses: '1-20', title: 'Beatitudes' },
      { book: 'Matthew', chapter: 5, verses: '21-48', title: 'Kingdom Standards' },
      { book: 'Matthew', chapter: 6, verses: '1-18', title: 'Prayer and Fasting' },
      { book: 'Matthew', chapter: 6, verses: '19-34', title: 'Do Not Worry' },
      { book: 'Matthew', chapter: 7, verses: '1-29', title: 'Build on the Rock' },
      { book: 'Matthew', chapter: 8, verses: '1-27', title: 'Miracles' },
      { book: 'Matthew', chapter: 9, verses: '1-38', title: 'Healing and Calling' },
      { book: 'Matthew', chapter: 10, verses: '1-42', title: 'Sending the Twelve' },
      { book: 'Matthew', chapter: 11, verses: '1-30', title: 'Come to Me' },
      { book: 'Matthew', chapter: 13, verses: '1-23', title: 'Parable of the Sower' },
      { book: 'Matthew', chapter: 13, verses: '24-52', title: 'Kingdom Parables' },
      { book: 'Matthew', chapter: 14, verses: '13-36', title: 'Walking on Water' },
      { book: 'Matthew', chapter: 16, verses: '13-28', title: 'Who Do You Say I Am' },
      { book: 'Matthew', chapter: 18, verses: '1-35', title: 'Forgiveness' },
      { book: 'Matthew', chapter: 20, verses: '1-34', title: 'First Will Be Last' },
      { book: 'Matthew', chapter: 21, verses: '1-22', title: 'Triumphal Entry' },
      { book: 'Matthew', chapter: 22, verses: '1-46', title: 'Wedding Feast' },
      { book: 'Matthew', chapter: 24, verses: '1-51', title: 'End Times' },
      { book: 'Matthew', chapter: 25, verses: '31-46', title: 'Sheep and Goats' },
      { book: 'Matthew', chapter: 26, verses: '1-46', title: 'Last Supper' },
      { book: 'Matthew', chapter: 26, verses: '47-75', title: 'Arrest' },
      { book: 'Matthew', chapter: 27, verses: '1-44', title: 'Crucifixion' },
      { book: 'Matthew', chapter: 27, verses: '45-66', title: 'Death' },
      { book: 'Matthew', chapter: 28, verses: '1-10', title: 'Resurrection' },
      { book: 'Matthew', chapter: 28, verses: '16-20', title: 'Great Commission' },
    ],
  },
  {
    id: 3,
    plan_type: 'gospel_of_mark',
    title: 'Gospel of Mark',
    description: 'The Servant King in action',
    category: 'Gospels',
    total_days: 16,
    icon: 'flash',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Mark', chapter: 1, verses: '1-20', title: 'Beginning of Ministry' },
      { book: 'Mark', chapter: 1, verses: '21-45', title: 'Authority Over Demons' },
      { book: 'Mark', chapter: 2, verses: '1-28', title: 'Forgiving and Healing' },
      { book: 'Mark', chapter: 4, verses: '1-41', title: 'Parables and Faith' },
      { book: 'Mark', chapter: 5, verses: '1-43', title: 'Power Over Death' },
      { book: 'Mark', chapter: 6, verses: '1-56', title: 'Feeding 5000' },
      { book: 'Mark', chapter: 8, verses: '1-38', title: 'Who Do You Say I Am' },
      { book: 'Mark', chapter: 9, verses: '1-50', title: 'Transfiguration' },
      { book: 'Mark', chapter: 10, verses: '1-52', title: 'The Last Shall Be First' },
      { book: 'Mark', chapter: 11, verses: '1-33', title: 'Triumphal Entry' },
      { book: 'Mark', chapter: 12, verses: '1-44', title: 'Greatest Commandment' },
      { book: 'Mark', chapter: 13, verses: '1-37', title: 'Watch and Pray' },
      { book: 'Mark', chapter: 14, verses: '1-52', title: 'Last Supper' },
      { book: 'Mark', chapter: 14, verses: '53-72', title: 'Betrayal' },
      { book: 'Mark', chapter: 15, verses: '1-47', title: 'Crucifixion' },
      { book: 'Mark', chapter: 16, verses: '1-20', title: 'Resurrection' },
    ],
  },
  {
    id: 4,
    plan_type: 'gospel_of_luke',
    title: 'Gospel of Luke',
    description: 'Jesus the perfect man',
    category: 'Gospels',
    total_days: 24,
    icon: 'heart',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Luke', chapter: 1, verses: '1-38', title: 'Announcements' },
      { book: 'Luke', chapter: 2, verses: '1-20', title: 'Birth of Jesus' },
      { book: 'Luke', chapter: 3, verses: '1-38', title: 'John the Baptist' },
      { book: 'Luke', chapter: 4, verses: '1-44', title: 'Temptation and Ministry' },
      { book: 'Luke', chapter: 5, verses: '1-39', title: 'Calling Disciples' },
      { book: 'Luke', chapter: 6, verses: '1-49', title: 'Sermon on the Plain' },
      { book: 'Luke', chapter: 7, verses: '1-50', title: 'Faith and Forgiveness' },
      { book: 'Luke', chapter: 8, verses: '1-56', title: 'Parables and Miracles' },
      { book: 'Luke', chapter: 9, verses: '1-62', title: 'Sending the Twelve' },
      { book: 'Luke', chapter: 10, verses: '1-42', title: 'Good Samaritan' },
      { book: 'Luke', chapter: 11, verses: '1-54', title: 'Teach Us to Pray' },
      { book: 'Luke', chapter: 12, verses: '1-59', title: 'Do Not Worry' },
      { book: 'Luke', chapter: 14, verses: '1-35', title: 'Cost of Discipleship' },
      { book: 'Luke', chapter: 15, verses: '1-32', title: 'Lost and Found' },
      { book: 'Luke', chapter: 16, verses: '1-31', title: 'Rich Man and Lazarus' },
      { book: 'Luke', chapter: 17, verses: '1-37', title: 'Faith and Kingdom' },
      { book: 'Luke', chapter: 18, verses: '1-43', title: 'Persistent Prayer' },
      { book: 'Luke', chapter: 19, verses: '1-48', title: 'Zacchaeus' },
      { book: 'Luke', chapter: 21, verses: '1-38', title: 'End Times' },
      { book: 'Luke', chapter: 22, verses: '1-71', title: 'Last Supper' },
      { book: 'Luke', chapter: 23, verses: '1-56', title: 'Crucifixion' },
      { book: 'Luke', chapter: 24, verses: '1-12', title: 'Empty Tomb' },
      { book: 'Luke', chapter: 24, verses: '13-35', title: 'Road to Emmaus' },
      { book: 'Luke', chapter: 24, verses: '36-53', title: 'Ascension' },
    ],
  },

  // ===== TOPICAL STUDIES =====
  {
    id: 5,
    plan_type: 'overcoming_anxiety',
    title: 'Overcoming Anxiety',
    description: 'Find peace through scripture',
    category: 'Topical',
    total_days: 7,
    icon: 'heart',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Philippians', chapter: 4, verses: '4-9', title: 'Peace of God' },
      { book: 'Matthew', chapter: 6, verses: '25-34', title: 'Do Not Worry' },
      { book: '1 Peter', chapter: 5, verses: '6-11', title: 'Cast Your Anxieties' },
      { book: 'Isaiah', chapter: 41, verses: '10-13', title: 'Fear Not' },
      { book: 'Psalm', chapter: 23, verses: '1-6', title: 'The Lord is My Shepherd' },
      { book: 'Psalm', chapter: 46, verses: '1-11', title: 'God is Our Refuge' },
      { book: '2 Timothy', chapter: 1, verses: '7-10', title: 'Power, Love, Self-Discipline' },
    ],
  },
  {
    id: 6,
    plan_type: 'prayer_power',
    title: 'Power of Prayer',
    description: 'Deepening your prayer life',
    category: 'Topical',
    total_days: 14,
    icon: 'hand-right',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Matthew', chapter: 6, verses: '5-15', title: 'The Lord\'s Prayer' },
      { book: 'Luke', chapter: 11, verses: '1-13', title: 'Ask, Seek, Knock' },
      { book: 'James', chapter: 5, verses: '13-18', title: 'Prayer of Faith' },
      { book: '1 Thessalonians', chapter: 5, verses: '16-18', title: 'Pray Without Ceasing' },
      { book: 'Philippians', chapter: 4, verses: '6-7', title: 'Peace Through Prayer' },
      { book: 'Ephesians', chapter: 6, verses: '18-20', title: 'Praying Always' },
      { book: 'Colossians', chapter: 4, verses: '2-4', title: 'Devote to Prayer' },
      { book: 'Romans', chapter: 8, verses: '26-27', title: 'Spirit Helps Us Pray' },
      { book: 'Hebrews', chapter: 4, verses: '14-16', title: 'Approach the Throne' },
      { book: '1 John', chapter: 5, verses: '14-15', title: 'Confidence in Prayer' },
      { book: 'Psalm', chapter: 145, verses: '18-19', title: 'Near to All Who Call' },
      { book: 'Jeremiah', chapter: 33, verses: '3', title: 'Call to Me' },
      { book: 'Matthew', chapter: 7, verses: '7-11', title: 'Good Gifts' },
      { book: 'John', chapter: 15, verses: '7-17', title: 'Remain in Me' },
    ],
  },
  {
    id: 7,
    plan_type: 'faith_foundations',
    title: 'Foundations of Faith',
    description: 'Build your faith on solid ground',
    category: 'Topical',
    total_days: 21,
    icon: 'star',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Hebrews', chapter: 11, verses: '1-6', title: 'What is Faith' },
      { book: 'Romans', chapter: 10, verses: '9-17', title: 'Faith Comes by Hearing' },
      { book: 'James', chapter: 2, verses: '14-26', title: 'Faith and Works' },
      { book: 'Ephesians', chapter: 2, verses: '8-10', title: 'Saved by Grace' },
      { book: 'John', chapter: 3, verses: '16-21', title: 'Born Again' },
      { book: 'Romans', chapter: 8, verses: '1-11', title: 'Life in the Spirit' },
      { book: '2 Corinthians', chapter: 5, verses: '17-21', title: 'New Creation' },
      { book: 'Galatians', chapter: 2, verses: '20-21', title: 'Crucified with Christ' },
      { book: 'Colossians', chapter: 2, verses: '6-15', title: 'Rooted in Christ' },
      { book: '1 Peter', chapter: 1, verses: '3-9', title: 'Living Hope' },
      { book: 'Romans', chapter: 5, verses: '1-11', title: 'Peace with God' },
      { book: 'John', chapter: 1, verses: '12-13', title: 'Children of God' },
      { book: 'Titus', chapter: 3, verses: '4-7', title: 'Mercy and Grace' },
      { book: 'Ephesians', chapter: 1, verses: '3-14', title: 'Spiritual Blessings' },
      { book: '1 John', chapter: 5, verses: '11-13', title: 'Eternal Life' },
      { book: 'Romans', chapter: 6, verses: '1-14', title: 'Dead to Sin' },
      { book: 'Philippians', chapter: 3, verses: '7-14', title: 'Press On' },
      { book: '2 Timothy', chapter: 1, verses: '8-14', title: 'Guard the Deposit' },
      { book: 'Hebrews', chapter: 6, verses: '10-20', title: 'Hope as an Anchor' },
      { book: '1 Corinthians', chapter: 15, verses: '1-11', title: 'Gospel First' },
      { book: 'Matthew', chapter: 7, verses: '24-29', title: 'Wise Builder' },
    ],
  },
  {
    id: 8,
    plan_type: 'love_and_relationships',
    title: 'Love & Relationships',
    description: 'Biblical perspective on love',
    category: 'Topical',
    total_days: 10,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: '1 Corinthians', chapter: 13, verses: '1-13', title: 'Love is Patient' },
      { book: 'John', chapter: 13, verses: '34-35', title: 'Love One Another' },
      { book: '1 John', chapter: 4, verses: '7-21', title: 'God is Love' },
      { book: 'Romans', chapter: 12, verses: '9-21', title: 'Sincere Love' },
      { book: 'Ephesians', chapter: 5, verses: '1-2', title: 'Walk in Love' },
      { book: 'Colossians', chapter: 3, verses: '12-17', title: 'Put on Love' },
      { book: 'Matthew', chapter: 22, verses: '36-40', title: 'Greatest Commandment' },
      { book: 'John', chapter: 15, verses: '9-17', title: 'Remain in My Love' },
      { book: '1 Peter', chapter: 4, verses: '8-11', title: 'Love Covers' },
      { book: 'Galatians', chapter: 5, verses: '13-15', title: 'Serve in Love' },
    ],
  },
  {
    id: 9,
    plan_type: 'forgiveness_freedom',
    title: 'Forgiveness & Freedom',
    description: 'Experience the power of forgiveness',
    category: 'Topical',
    total_days: 7,
    icon: 'hand-left',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Matthew', chapter: 6, verses: '14-15', title: 'Forgive Others' },
      { book: 'Ephesians', chapter: 4, verses: '31-32', title: 'Be Kind' },
      { book: 'Colossians', chapter: 3, verses: '12-13', title: 'Bear with Each Other' },
      { book: 'Matthew', chapter: 18, verses: '21-35', title: 'Seventy Times Seven' },
      { book: 'Luke', chapter: 23, verses: '33-34', title: 'Father Forgive Them' },
      { book: '1 John', chapter: 1, verses: '8-10', title: 'If We Confess' },
      { book: 'Psalm', chapter: 103, verses: '8-14', title: 'As Far as East from West' },
    ],
  },
  {
    id: 10,
    plan_type: 'spiritual_warfare',
    title: 'Spiritual Warfare',
    description: 'Stand strong in spiritual battles',
    category: 'Topical',
    total_days: 14,
    icon: 'shield',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Ephesians', chapter: 6, verses: '10-18', title: 'Armor of God' },
      { book: '2 Corinthians', chapter: 10, verses: '3-5', title: 'Spiritual Weapons' },
      { book: 'James', chapter: 4, verses: '7-10', title: 'Resist the Devil' },
      { book: '1 Peter', chapter: 5, verses: '8-11', title: 'Be Alert' },
      { book: 'Romans', chapter: 8, verses: '31-39', title: 'More Than Conquerors' },
      { book: '2 Timothy', chapter: 2, verses: '1-7', title: 'Good Soldier' },
      { book: 'Psalm', chapter: 91, verses: '1-16', title: 'Under His Wings' },
      { book: '1 John', chapter: 4, verses: '4', title: 'Greater is He' },
      { book: 'Luke', chapter: 10, verses: '17-20', title: 'Authority Over Enemy' },
      { book: 'Colossians', chapter: 2, verses: '13-15', title: 'Disarmed Powers' },
      { book: 'Revelation', chapter: 12, verses: '10-11', title: 'Overcome by Blood' },
      { book: '2 Thessalonians', chapter: 3, verses: '1-5', title: 'Lord is Faithful' },
      { book: 'Hebrews', chapter: 2, verses: '14-15', title: 'Victory Over Death' },
      { book: '1 Corinthians', chapter: 15, verses: '57-58', title: 'Victory Through Christ' },
    ],
  },

  // ===== WISDOM BOOKS =====
  {
    id: 11,
    plan_type: 'proverbs_wisdom',
    title: 'Proverbs Wisdom',
    description: 'Daily wisdom for life',
    category: 'Wisdom',
    total_days: 31,
    icon: 'bulb',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Proverbs', chapter: 1, verses: '1-7', title: 'Beginning of Knowledge' },
      { book: 'Proverbs', chapter: 2, verses: '1-11', title: 'Benefits of Wisdom' },
      { book: 'Proverbs', chapter: 3, verses: '1-12', title: 'Trust in the Lord' },
      { book: 'Proverbs', chapter: 3, verses: '13-26', title: 'Wisdom is Precious' },
      { book: 'Proverbs', chapter: 4, verses: '1-13', title: 'Get Wisdom' },
      { book: 'Proverbs', chapter: 4, verses: '14-27', title: 'Guard Your Heart' },
      { book: 'Proverbs', chapter: 5, verses: '1-23', title: 'Fidelity' },
      { book: 'Proverbs', chapter: 6, verses: '1-19', title: 'Seven Things' },
      { book: 'Proverbs', chapter: 6, verses: '20-35', title: 'Warning' },
      { book: 'Proverbs', chapter: 7, verses: '1-27', title: 'Keep My Words' },
      { book: 'Proverbs', chapter: 8, verses: '1-21', title: 'Wisdom Calls' },
      { book: 'Proverbs', chapter: 9, verses: '1-18', title: 'Fear of the Lord' },
      { book: 'Proverbs', chapter: 10, verses: '1-16', title: 'Wise Son' },
      { book: 'Proverbs', chapter: 11, verses: '1-15', title: 'Integrity' },
      { book: 'Proverbs', chapter: 12, verses: '1-14', title: 'Truthful Lips' },
      { book: 'Proverbs', chapter: 13, verses: '1-13', title: 'Walk with Wise' },
      { book: 'Proverbs', chapter: 14, verses: '1-17', title: 'Wise Woman Builds' },
      { book: 'Proverbs', chapter: 15, verses: '1-17', title: 'Gentle Answer' },
      { book: 'Proverbs', chapter: 16, verses: '1-16', title: 'Commit to Lord' },
      { book: 'Proverbs', chapter: 17, verses: '1-14', title: 'Better a Dry Crust' },
      { book: 'Proverbs', chapter: 18, verses: '1-13', title: 'Name of the Lord' },
      { book: 'Proverbs', chapter: 19, verses: '1-14', title: 'Plans of the Heart' },
      { book: 'Proverbs', chapter: 20, verses: '1-15', title: 'Deep Waters' },
      { book: 'Proverbs', chapter: 21, verses: '1-16', title: 'To Do Right' },
      { book: 'Proverbs', chapter: 22, verses: '1-16', title: 'Good Name' },
      { book: 'Proverbs', chapter: 23, verses: '12-25', title: 'Apply Your Heart' },
      { book: 'Proverbs', chapter: 24, verses: '1-22', title: 'Wisdom Builds' },
      { book: 'Proverbs', chapter: 25, verses: '1-15', title: 'Timely Word' },
      { book: 'Proverbs', chapter: 27, verses: '1-14', title: 'Do Not Boast' },
      { book: 'Proverbs', chapter: 30, verses: '1-9', title: 'Two Things' },
      { book: 'Proverbs', chapter: 31, verses: '10-31', title: 'Noble Character' },
    ],
  },
  {
    id: 12,
    plan_type: 'psalms_of_praise',
    title: 'Psalms of Praise',
    description: '30 days of worship',
    category: 'Wisdom',
    total_days: 30,
    icon: 'musical-notes',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Psalm', chapter: 1, verses: '1-6', title: 'Blessed is the Man' },
      { book: 'Psalm', chapter: 8, verses: '1-9', title: 'Your Name is Majestic' },
      { book: 'Psalm', chapter: 19, verses: '1-14', title: 'Heavens Declare' },
      { book: 'Psalm', chapter: 23, verses: '1-6', title: 'The Lord is My Shepherd' },
      { book: 'Psalm', chapter: 24, verses: '1-10', title: 'The King of Glory' },
      { book: 'Psalm', chapter: 27, verses: '1-14', title: 'The Lord is My Light' },
      { book: 'Psalm', chapter: 34, verses: '1-22', title: 'Taste and See' },
      { book: 'Psalm', chapter: 42, verses: '1-11', title: 'As the Deer Pants' },
      { book: 'Psalm', chapter: 46, verses: '1-11', title: 'Be Still and Know' },
      { book: 'Psalm', chapter: 51, verses: '1-19', title: 'Create in Me' },
      { book: 'Psalm', chapter: 63, verses: '1-11', title: 'My Soul Thirsts' },
      { book: 'Psalm', chapter: 84, verses: '1-12', title: 'Better is One Day' },
      { book: 'Psalm', chapter: 90, verses: '1-17', title: 'Teach Us to Number' },
      { book: 'Psalm', chapter: 91, verses: '1-16', title: 'Dwelling Place' },
      { book: 'Psalm', chapter: 95, verses: '1-11', title: 'Come Let Us Sing' },
      { book: 'Psalm', chapter: 96, verses: '1-13', title: 'Sing a New Song' },
      { book: 'Psalm', chapter: 98, verses: '1-9', title: 'Make a Joyful Noise' },
      { book: 'Psalm', chapter: 100, verses: '1-5', title: 'Enter His Gates' },
      { book: 'Psalm', chapter: 103, verses: '1-22', title: 'Bless the Lord' },
      { book: 'Psalm', chapter: 107, verses: '1-43', title: 'Give Thanks' },
      { book: 'Psalm', chapter: 118, verses: '1-29', title: 'This is the Day' },
      { book: 'Psalm', chapter: 119, verses: '1-16', title: 'Your Word' },
      { book: 'Psalm', chapter: 121, verses: '1-8', title: 'I Lift Up My Eyes' },
      { book: 'Psalm', chapter: 130, verses: '1-8', title: 'Out of the Depths' },
      { book: 'Psalm', chapter: 139, verses: '1-24', title: 'You Know Me' },
      { book: 'Psalm', chapter: 145, verses: '1-21', title: 'I Will Exalt You' },
      { book: 'Psalm', chapter: 146, verses: '1-10', title: 'Praise the Lord' },
      { book: 'Psalm', chapter: 147, verses: '1-20', title: 'Great is Our Lord' },
      { book: 'Psalm', chapter: 148, verses: '1-14', title: 'Praise Him All' },
      { book: 'Psalm', chapter: 150, verses: '1-6', title: 'Let Everything Praise' },
    ],
  },
  {
    id: 13,
    plan_type: 'book_of_ecclesiastes',
    title: 'Ecclesiastes',
    description: 'Meaning and purpose in life',
    category: 'Wisdom',
    total_days: 12,
    icon: 'bulb',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Ecclesiastes', chapter: 1, verses: '1-11', title: 'Meaningless' },
      { book: 'Ecclesiastes', chapter: 1, verses: '12-18', title: 'Wisdom is Meaningless' },
      { book: 'Ecclesiastes', chapter: 2, verses: '1-26', title: 'Pleasures are Meaningless' },
      { book: 'Ecclesiastes', chapter: 3, verses: '1-22', title: 'A Time for Everything' },
      { book: 'Ecclesiastes', chapter: 4, verses: '1-16', title: 'Two are Better' },
      { book: 'Ecclesiastes', chapter: 5, verses: '1-20', title: 'Stand in Awe' },
      { book: 'Ecclesiastes', chapter: 7, verses: '1-29', title: 'Wisdom' },
      { book: 'Ecclesiastes', chapter: 9, verses: '1-18', title: 'One Fate' },
      { book: 'Ecclesiastes', chapter: 11, verses: '1-10', title: 'Cast Your Bread' },
      { book: 'Ecclesiastes', chapter: 12, verses: '1-8', title: 'Remember Your Creator' },
      { book: 'Ecclesiastes', chapter: 12, verses: '9-14', title: 'Fear God' },
      { book: 'Ecclesiastes', chapter: 3, verses: '11-15', title: 'He Has Made Everything Beautiful' },
    ],
  },

  // ===== NEW TESTAMENT LETTERS =====
  {
    id: 14,
    plan_type: 'romans_journey',
    title: 'Journey Through Romans',
    description: 'The gospel explained',
    category: 'New Testament',
    total_days: 16,
    icon: 'book',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Romans', chapter: 1, verses: '1-17', title: 'Power of the Gospel' },
      { book: 'Romans', chapter: 1, verses: '18-32', title: 'God\'s Wrath' },
      { book: 'Romans', chapter: 2, verses: '1-16', title: 'God\'s Righteous Judgment' },
      { book: 'Romans', chapter: 3, verses: '9-31', title: 'None Righteous' },
      { book: 'Romans', chapter: 5, verses: '1-11', title: 'Peace with God' },
      { book: 'Romans', chapter: 6, verses: '1-14', title: 'Dead to Sin' },
      { book: 'Romans', chapter: 7, verses: '1-25', title: 'Struggle with Sin' },
      { book: 'Romans', chapter: 8, verses: '1-17', title: 'Life in the Spirit' },
      { book: 'Romans', chapter: 8, verses: '18-39', title: 'More Than Conquerors' },
      { book: 'Romans', chapter: 10, verses: '1-21', title: 'Faith Comes by Hearing' },
      { book: 'Romans', chapter: 11, verses: '33-36', title: 'Doxology' },
      { book: 'Romans', chapter: 12, verses: '1-21', title: 'Living Sacrifice' },
      { book: 'Romans', chapter: 13, verses: '8-14', title: 'Love Fulfills the Law' },
      { book: 'Romans', chapter: 14, verses: '1-23', title: 'Weak and Strong' },
      { book: 'Romans', chapter: 15, verses: '1-13', title: 'Bear with Each Other' },
      { book: 'Romans', chapter: 16, verses: '25-27', title: 'Glory Forever' },
    ],
  },
  {
    id: 15,
    plan_type: 'ephesians_riches',
    title: 'Riches in Ephesians',
    description: 'Our identity in Christ',
    category: 'New Testament',
    total_days: 6,
    icon: 'star',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Ephesians', chapter: 1, verses: '1-14', title: 'Spiritual Blessings' },
      { book: 'Ephesians', chapter: 1, verses: '15-23', title: 'Prayer for the Church' },
      { book: 'Ephesians', chapter: 2, verses: '1-10', title: 'Made Alive in Christ' },
      { book: 'Ephesians', chapter: 2, verses: '11-22', title: 'One in Christ' },
      { book: 'Ephesians', chapter: 3, verses: '14-21', title: 'Rooted in Love' },
      { book: 'Ephesians', chapter: 4, verses: '1-16', title: 'Unity in the Body' },
    ],
  },
  {
    id: 16,
    plan_type: 'philippians_joy',
    title: 'Joy in Philippians',
    description: 'Rejoice in the Lord always',
    category: 'New Testament',
    total_days: 4,
    icon: 'happy',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Philippians', chapter: 1, verses: '1-26', title: 'To Live is Christ' },
      { book: 'Philippians', chapter: 2, verses: '1-18', title: 'Mind of Christ' },
      { book: 'Philippians', chapter: 3, verses: '1-21', title: 'Press On' },
      { book: 'Philippians', chapter: 4, verses: '1-23', title: 'Rejoice in the Lord' },
    ],
  },
  {
    id: 17,
    plan_type: 'colossians_supremacy',
    title: 'Supremacy of Christ',
    description: 'Christ is preeminent',
    category: 'New Testament',
    total_days: 4,
    icon: 'ribbon',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Colossians', chapter: 1, verses: '1-23', title: 'Supremacy of Christ' },
      { book: 'Colossians', chapter: 2, verses: '1-23', title: 'Freedom in Christ' },
      { book: 'Colossians', chapter: 3, verses: '1-17', title: 'Set Your Hearts' },
      { book: 'Colossians', chapter: 3, verses: '18-4:18', title: 'Christian Living' },
    ],
  },
  {
    id: 18,
    plan_type: 'james_practical',
    title: 'Practical Faith - James',
    description: 'Faith that works',
    category: 'New Testament',
    total_days: 5,
    icon: 'construct',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'James', chapter: 1, verses: '1-27', title: 'Trials and Temptations' },
      { book: 'James', chapter: 2, verses: '1-26', title: 'Faith and Works' },
      { book: 'James', chapter: 3, verses: '1-18', title: 'Taming the Tongue' },
      { book: 'James', chapter: 4, verses: '1-17', title: 'Submit to God' },
      { book: 'James', chapter: 5, verses: '1-20', title: 'Patience and Prayer' },
    ],
  },
  {
    id: 19,
    plan_type: 'first_peter_hope',
    title: 'Living Hope - 1 Peter',
    description: 'Hope in suffering',
    category: 'New Testament',
    total_days: 5,
    icon: 'heart',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: '1 Peter', chapter: 1, verses: '1-25', title: 'Living Hope' },
      { book: '1 Peter', chapter: 2, verses: '1-25', title: 'Living Stone' },
      { book: '1 Peter', chapter: 3, verses: '1-22', title: 'Suffering for Good' },
      { book: '1 Peter', chapter: 4, verses: '1-19', title: 'Living for God' },
      { book: '1 Peter', chapter: 5, verses: '1-14', title: 'Shepherd the Flock' },
    ],
  },
  {
    id: 20,
    plan_type: 'first_john_love',
    title: 'Walk in Love - 1 John',
    description: 'God is love',
    category: 'New Testament',
    total_days: 5,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: '1 John', chapter: 1, verses: '1-10', title: 'Walk in Light' },
      { book: '1 John', chapter: 2, verses: '1-17', title: 'Love Not the World' },
      { book: '1 John', chapter: 3, verses: '1-24', title: 'Children of God' },
      { book: '1 John', chapter: 4, verses: '1-21', title: 'God is Love' },
      { book: '1 John', chapter: 5, verses: '1-21', title: 'Overcoming the World' },
    ],
  },

  // ===== OLD TESTAMENT =====
  {
    id: 21,
    plan_type: 'genesis_beginnings',
    title: 'Genesis - Beginnings',
    description: 'In the beginning God',
    category: 'Old Testament',
    total_days: 50,
    icon: 'leaf',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Genesis', chapter: 1, verses: '1-31', title: 'Creation' },
      { book: 'Genesis', chapter: 2, verses: '1-25', title: 'Adam and Eve' },
      { book: 'Genesis', chapter: 3, verses: '1-24', title: 'The Fall' },
      { book: 'Genesis', chapter: 4, verses: '1-26', title: 'Cain and Abel' },
      { book: 'Genesis', chapter: 6, verses: '1-22', title: 'Noah' },
      { book: 'Genesis', chapter: 7, verses: '1-24', title: 'The Flood' },
      { book: 'Genesis', chapter: 8, verses: '1-22', title: 'New Beginning' },
      { book: 'Genesis', chapter: 9, verses: '1-29', title: 'God\'s Covenant' },
      { book: 'Genesis', chapter: 11, verses: '1-32', title: 'Tower of Babel' },
      { book: 'Genesis', chapter: 12, verses: '1-20', title: 'Call of Abram' },
      { book: 'Genesis', chapter: 15, verses: '1-21', title: 'God\'s Covenant with Abram' },
      { book: 'Genesis', chapter: 17, verses: '1-27', title: 'Abraham and Circumcision' },
      { book: 'Genesis', chapter: 18, verses: '1-33', title: 'Abraham Pleads' },
      { book: 'Genesis', chapter: 19, verses: '1-38', title: 'Sodom and Gomorrah' },
      { book: 'Genesis', chapter: 21, verses: '1-34', title: 'Birth of Isaac' },
      { book: 'Genesis', chapter: 22, verses: '1-24', title: 'Abraham Tested' },
      { book: 'Genesis', chapter: 24, verses: '1-67', title: 'Isaac and Rebekah' },
      { book: 'Genesis', chapter: 25, verses: '19-34', title: 'Jacob and Esau' },
      { book: 'Genesis', chapter: 27, verses: '1-46', title: 'Jacob\'s Deception' },
      { book: 'Genesis', chapter: 28, verses: '10-22', title: 'Jacob\'s Ladder' },
      { book: 'Genesis', chapter: 29, verses: '1-35', title: 'Jacob Marries' },
      { book: 'Genesis', chapter: 32, verses: '22-32', title: 'Wrestling with God' },
      { book: 'Genesis', chapter: 33, verses: '1-20', title: 'Jacob Meets Esau' },
      { book: 'Genesis', chapter: 37, verses: '1-36', title: 'Joseph\'s Dreams' },
      { book: 'Genesis', chapter: 39, verses: '1-23', title: 'Joseph and Potiphar' },
      { book: 'Genesis', chapter: 40, verses: '1-23', title: 'Joseph Interprets Dreams' },
      { book: 'Genesis', chapter: 41, verses: '1-57', title: 'Pharaoh\'s Dreams' },
      { book: 'Genesis', chapter: 42, verses: '1-38', title: 'Brothers Go to Egypt' },
      { book: 'Genesis', chapter: 43, verses: '1-34', title: 'Second Journey' },
      { book: 'Genesis', chapter: 44, verses: '1-34', title: 'Joseph\'s Silver Cup' },
      { book: 'Genesis', chapter: 45, verses: '1-28', title: 'Joseph Reveals Himself' },
      { book: 'Genesis', chapter: 46, verses: '1-34', title: 'Jacob Goes to Egypt' },
      { book: 'Genesis', chapter: 48, verses: '1-22', title: 'Jacob Blesses' },
      { book: 'Genesis', chapter: 49, verses: '1-33', title: 'Jacob Blesses His Sons' },
      { book: 'Genesis', chapter: 50, verses: '15-26', title: 'Joseph\'s Assurance' },
      { book: 'Genesis', chapter: 1, verses: '26-27', title: 'Made in His Image' },
      { book: 'Genesis', chapter: 2, verses: '15-17', title: 'Garden of Eden' },
      { book: 'Genesis', chapter: 5, verses: '21-24', title: 'Enoch Walked with God' },
      { book: 'Genesis', chapter: 6, verses: '5-9', title: 'Noah Found Favor' },
      { book: 'Genesis', chapter: 12, verses: '1-3', title: 'The Call' },
      { book: 'Genesis', chapter: 13, verses: '14-18', title: 'Land Promise' },
      { book: 'Genesis', chapter: 15, verses: '1-6', title: 'Counted as Righteousness' },
      { book: 'Genesis', chapter: 16, verses: '7-13', title: 'Hagar' },
      { book: 'Genesis', chapter: 18, verses: '16-33', title: 'Will Not the Judge' },
      { book: 'Genesis', chapter: 22, verses: '1-14', title: 'God Will Provide' },
      { book: 'Genesis', chapter: 26, verses: '1-25', title: 'Isaac and the Wells' },
      { book: 'Genesis', chapter: 28, verses: '1-9', title: 'Isaac Blesses Jacob' },
      { book: 'Genesis', chapter: 31, verses: '1-21', title: 'Jacob Flees' },
      { book: 'Genesis', chapter: 35, verses: '1-15', title: 'Jacob Returns to Bethel' },
      { book: 'Genesis', chapter: 50, verses: '15-21', title: 'You Meant Evil' },
    ],
  },
  {
    id: 22,
    plan_type: 'exodus_deliverance',
    title: 'Exodus - Deliverance',
    description: 'God delivers His people',
    category: 'Old Testament',
    total_days: 40,
    icon: 'walk',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Exodus', chapter: 1, verses: '1-22', title: 'Israelites Oppressed' },
      { book: 'Exodus', chapter: 2, verses: '1-25', title: 'Birth of Moses' },
      { book: 'Exodus', chapter: 3, verses: '1-22', title: 'Burning Bush' },
      { book: 'Exodus', chapter: 4, verses: '1-31', title: 'Signs for Moses' },
      { book: 'Exodus', chapter: 5, verses: '1-23', title: 'Bricks Without Straw' },
      { book: 'Exodus', chapter: 6, verses: '1-13', title: 'God Promises' },
      { book: 'Exodus', chapter: 7, verses: '1-25', title: 'First Plague' },
      { book: 'Exodus', chapter: 8, verses: '1-32', title: 'Frogs and Gnats' },
      { book: 'Exodus', chapter: 9, verses: '1-35', title: 'More Plagues' },
      { book: 'Exodus', chapter: 10, verses: '1-29', title: 'Locusts and Darkness' },
      { book: 'Exodus', chapter: 11, verses: '1-10', title: 'Tenth Plague' },
      { book: 'Exodus', chapter: 12, verses: '1-30', title: 'Passover' },
      { book: 'Exodus', chapter: 12, verses: '31-51', title: 'The Exodus' },
      { book: 'Exodus', chapter: 13, verses: '17-22', title: 'Pillar of Cloud' },
      { book: 'Exodus', chapter: 14, verses: '1-31', title: 'Red Sea' },
      { book: 'Exodus', chapter: 15, verses: '1-21', title: 'Song of Moses' },
      { book: 'Exodus', chapter: 16, verses: '1-36', title: 'Manna' },
      { book: 'Exodus', chapter: 17, verses: '1-16', title: 'Water from the Rock' },
      { book: 'Exodus', chapter: 19, verses: '1-25', title: 'At Mount Sinai' },
      { book: 'Exodus', chapter: 20, verses: '1-21', title: 'Ten Commandments' },
      { book: 'Exodus', chapter: 24, verses: '1-18', title: 'Covenant Confirmed' },
      { book: 'Exodus', chapter: 25, verses: '1-22', title: 'Tabernacle' },
      { book: 'Exodus', chapter: 28, verses: '1-43', title: 'Priestly Garments' },
      { book: 'Exodus', chapter: 29, verses: '38-46', title: 'Daily Offerings' },
      { book: 'Exodus', chapter: 31, verses: '12-18', title: 'Sabbath' },
      { book: 'Exodus', chapter: 32, verses: '1-35', title: 'Golden Calf' },
      { book: 'Exodus', chapter: 33, verses: '1-23', title: 'My Presence' },
      { book: 'Exodus', chapter: 34, verses: '1-35', title: 'New Tablets' },
      { book: 'Exodus', chapter: 40, verses: '1-38', title: 'Glory Fills' },
      { book: 'Exodus', chapter: 3, verses: '13-14', title: 'I AM' },
      { book: 'Exodus', chapter: 6, verses: '2-8', title: 'I Am the Lord' },
      { book: 'Exodus', chapter: 12, verses: '21-28', title: 'Passover Instructions' },
      { book: 'Exodus', chapter: 14, verses: '10-14', title: 'The Lord Will Fight' },
      { book: 'Exodus', chapter: 15, verses: '22-27', title: 'I Am the Lord Who Heals' },
      { book: 'Exodus', chapter: 17, verses: '8-16', title: 'Amalek Defeated' },
      { book: 'Exodus', chapter: 18, verses: '1-27', title: 'Jethro Visits' },
      { book: 'Exodus', chapter: 20, verses: '22-26', title: 'Altar' },
      { book: 'Exodus', chapter: 23, verses: '20-33', title: 'God\'s Angel' },
      { book: 'Exodus', chapter: 33, verses: '12-23', title: 'Show Me Your Glory' },
      { book: 'Exodus', chapter: 34, verses: '29-35', title: 'Radiant Face' },
    ],
  },

  // ===== NEW BELIEVER =====
  {
    id: 23,
    plan_type: 'new_believer_basics',
    title: 'New Believer Basics',
    description: 'Foundation for your faith',
    category: 'For New Believers',
    total_days: 21,
    icon: 'star',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'John', chapter: 3, verses: '1-21', title: 'Born Again' },
      { book: 'Romans', chapter: 3, verses: '21-31', title: 'Righteousness Through Faith' },
      { book: 'Ephesians', chapter: 2, verses: '1-10', title: 'Made Alive in Christ' },
      { book: '1 John', chapter: 1, verses: '1-10', title: 'The Word of Life' },
      { book: 'Romans', chapter: 8, verses: '1-17', title: 'Life Through the Spirit' },
      { book: 'Galatians', chapter: 5, verses: '16-26', title: 'Life by the Spirit' },
      { book: 'Matthew', chapter: 28, verses: '16-20', title: 'Great Commission' },
      { book: 'Acts', chapter: 2, verses: '37-47', title: 'The Fellowship' },
      { book: '2 Corinthians', chapter: 5, verses: '17-21', title: 'New Creation' },
      { book: 'Colossians', chapter: 2, verses: '6-15', title: 'Rooted in Christ' },
      { book: '1 Peter', chapter: 2, verses: '1-12', title: 'Living Stones' },
      { book: 'Hebrews', chapter: 10, verses: '19-25', title: 'Draw Near' },
      { book: 'John', chapter: 15, verses: '1-17', title: 'Remain in Me' },
      { book: 'Romans', chapter: 6, verses: '1-14', title: 'Dead to Sin' },
      { book: 'Ephesians', chapter: 4, verses: '17-32', title: 'New Life' },
      { book: 'Philippians', chapter: 3, verses: '7-14', title: 'Knowing Christ' },
      { book: '1 Thessalonians', chapter: 5, verses: '12-28', title: 'Final Instructions' },
      { book: '2 Timothy', chapter: 2, verses: '14-26', title: 'Worker Approved' },
      { book: 'James', chapter: 1, verses: '19-27', title: 'Do What It Says' },
      { book: '1 John', chapter: 2, verses: '12-17', title: 'Do Not Love the World' },
      { book: 'Jude', chapter: 1, verses: '17-25', title: 'Build Yourselves Up' },
    ],
  },

  // Continue with more categories...
  // I'll add more themed plans to reach 100+
];

// Helper function to get plan by type
export const getPlanByType = (planType) => {
  return READING_PLANS.find(plan => plan.plan_type === planType);
};

// Helper function to get plans by category
export const getPlansByCategory = (category) => {
  if (!category) return READING_PLANS;
  return READING_PLANS.filter(plan => plan.category === category);
};

// Get all unique categories
export const getCategories = () => {
  const categories = [...new Set(READING_PLANS.map(plan => plan.category))];
  return categories.sort();
};

// Get verse for a specific day of a plan
export const getPlanVerse = (planType, day) => {
  const plan = getPlanByType(planType);
  if (!plan || !plan.verses || day < 0 || day >= plan.verses.length) {
    return null;
  }
  return plan.verses[day];
};

