import theme from './theme';

// Additional 100+ Reading Plans
// This extends the base reading plans with more comprehensive options

export const EXTENDED_READING_PLANS = [
  // ===== ACTS & EARLY CHURCH (5 plans) =====
  {
    id: 24,
    plan_type: 'book_of_acts',
    title: 'Acts - Early Church',
    description: 'The birth and growth of the church',
    category: 'New Testament',
    total_days: 28,
    icon: 'flame',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 28 }, (_, i) => ({
      book: 'Acts',
      chapter: i + 1,
      verses: '1-47',
      title: `Acts Chapter ${i + 1}`
    })),
  },
  {
    id: 25,
    plan_type: 'paul_missionary_journeys',
    title: 'Paul\'s Missionary Journeys',
    description: 'Follow Paul\'s travels in Acts',
    category: 'New Testament',
    total_days: 14,
    icon: 'map',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Acts', chapter: 13, verses: '1-52', title: 'First Journey Begins' },
      { book: 'Acts', chapter: 14, verses: '1-28', title: 'Iconium and Lystra' },
      { book: 'Acts', chapter: 15, verses: '36-41', title: 'Second Journey Begins' },
      { book: 'Acts', chapter: 16, verses: '6-40', title: 'Macedonia' },
      { book: 'Acts', chapter: 17, verses: '1-34', title: 'Thessalonica and Athens' },
      { book: 'Acts', chapter: 18, verses: '1-28', title: 'Corinth' },
      { book: 'Acts', chapter: 19, verses: '1-41', title: 'Ephesus' },
      { book: 'Acts', chapter: 20, verses: '1-38', title: 'Journey to Jerusalem' },
      { book: 'Acts', chapter: 21, verses: '1-40', title: 'Arrival in Jerusalem' },
      { book: 'Acts', chapter: 22, verses: '1-30', title: 'Paul\'s Defense' },
      { book: 'Acts', chapter: 27, verses: '1-44', title: 'Shipwreck' },
      { book: 'Acts', chapter: 28, verses: '1-31', title: 'Rome' },
      { book: '2 Corinthians', chapter: 11, verses: '23-33', title: 'Paul\'s Sufferings' },
      { book: 'Philippians', chapter: 1, verses: '12-30', title: 'Advance of the Gospel' },
    ],
  },
  {
    id: 26,
    plan_type: 'pentecost_power',
    title: 'Pentecost & The Spirit',
    description: 'Holy Spirit in the early church',
    category: 'New Testament',
    total_days: 7,
    icon: 'flame',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Acts', chapter: 1, verses: '1-11', title: 'Ascension' },
      { book: 'Acts', chapter: 2, verses: '1-47', title: 'Day of Pentecost' },
      { book: 'Acts', chapter: 4, verses: '23-37', title: 'Filled with the Spirit' },
      { book: 'Acts', chapter: 8, verses: '26-40', title: 'Philip and the Ethiopian' },
      { book: 'Acts', chapter: 10, verses: '44-48', title: 'Spirit Falls on Gentiles' },
      { book: 'Acts', chapter: 13, verses: '1-12', title: 'Set Apart by the Spirit' },
      { book: 'Romans', chapter: 8, verses: '1-17', title: 'Life in the Spirit' },
    ],
  },

  // ===== PAUL'S LETTERS (20 plans) =====
  {
    id: 27,
    plan_type: 'galatians_freedom',
    title: 'Freedom in Galatians',
    description: 'Liberty in Christ',
    category: 'Paul\'s Letters',
    total_days: 6,
    icon: 'key',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 6 }, (_, i) => ({
      book: 'Galatians',
      chapter: i + 1,
      verses: '1-29',
      title: `Galatians ${i + 1}`
    })),
  },
  {
    id: 28,
    plan_type: 'first_corinthians',
    title: '1 Corinthians - Church Life',
    description: 'Practical church issues',
    category: 'Paul\'s Letters',
    total_days: 16,
    icon: 'people',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 16 }, (_, i) => ({
      book: '1 Corinthians',
      chapter: i + 1,
      verses: '1-58',
      title: `1 Corinthians ${i + 1}`
    })),
  },
  {
    id: 29,
    plan_type: 'second_corinthians',
    title: '2 Corinthians - Ministry',
    description: 'Paul\'s ministry and suffering',
    category: 'Paul\'s Letters',
    total_days: 13,
    icon: 'heart',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 13 }, (_, i) => ({
      book: '2 Corinthians',
      chapter: i + 1,
      verses: '1-24',
      title: `2 Corinthians ${i + 1}`
    })),
  },
  {
    id: 30,
    plan_type: 'first_thessalonians',
    title: '1 Thessalonians',
    description: 'Living for Christ\'s return',
    category: 'Paul\'s Letters',
    total_days: 5,
    icon: 'time',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 5 }, (_, i) => ({
      book: '1 Thessalonians',
      chapter: i + 1,
      verses: '1-28',
      title: `1 Thessalonians ${i + 1}`
    })),
  },
  {
    id: 31,
    plan_type: 'second_thessalonians',
    title: '2 Thessalonians',
    description: 'Stand firm in truth',
    category: 'Paul\'s Letters',
    total_days: 3,
    icon: 'shield',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: '2 Thessalonians',
      chapter: i + 1,
      verses: '1-18',
      title: `2 Thessalonians ${i + 1}`
    })),
  },
  {
    id: 32,
    plan_type: 'first_timothy',
    title: '1 Timothy - Leadership',
    description: 'Instructions for church leaders',
    category: 'Paul\'s Letters',
    total_days: 6,
    icon: 'ribbon',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 6 }, (_, i) => ({
      book: '1 Timothy',
      chapter: i + 1,
      verses: '1-20',
      title: `1 Timothy ${i + 1}`
    })),
  },
  {
    id: 33,
    plan_type: 'second_timothy',
    title: '2 Timothy - Final Words',
    description: 'Paul\'s last letter',
    category: 'Paul\'s Letters',
    total_days: 4,
    icon: 'document-text',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 4 }, (_, i) => ({
      book: '2 Timothy',
      chapter: i + 1,
      verses: '1-18',
      title: `2 Timothy ${i + 1}`
    })),
  },
  {
    id: 34,
    plan_type: 'titus',
    title: 'Titus - Sound Doctrine',
    description: 'Teaching and living truth',
    category: 'Paul\'s Letters',
    total_days: 3,
    icon: 'book',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: 'Titus',
      chapter: i + 1,
      verses: '1-16',
      title: `Titus ${i + 1}`
    })),
  },
  {
    id: 35,
    plan_type: 'philemon',
    title: 'Philemon - Forgiveness',
    description: 'A letter about reconciliation',
    category: 'Paul\'s Letters',
    total_days: 1,
    icon: 'hand-left',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Philemon', chapter: 1, verses: '1-25', title: 'Plea for Onesimus' },
    ],
  },

  // ===== HEBREWS & GENERAL EPISTLES (10 plans) =====
  {
    id: 36,
    plan_type: 'hebrews_superior',
    title: 'Hebrews - Christ is Superior',
    description: 'The supremacy of Christ',
    category: 'General Epistles',
    total_days: 13,
    icon: 'ribbon',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 13 }, (_, i) => ({
      book: 'Hebrews',
      chapter: i + 1,
      verses: '1-40',
      title: `Hebrews ${i + 1}`
    })),
  },
  {
    id: 37,
    plan_type: 'second_peter',
    title: '2 Peter - Growing in Grace',
    description: 'Grow in knowledge of Christ',
    category: 'General Epistles',
    total_days: 3,
    icon: 'trending-up',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: '2 Peter',
      chapter: i + 1,
      verses: '1-22',
      title: `2 Peter ${i + 1}`
    })),
  },
  {
    id: 38,
    plan_type: 'second_john',
    title: '2 John - Truth & Love',
    description: 'Walk in truth and love',
    category: 'General Epistles',
    total_days: 1,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: '2 John', chapter: 1, verses: '1-13', title: 'Walk in Truth' },
    ],
  },
  {
    id: 39,
    plan_type: 'third_john',
    title: '3 John - Hospitality',
    description: 'Supporting fellow workers',
    category: 'General Epistles',
    total_days: 1,
    icon: 'home',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: '3 John', chapter: 1, verses: '1-14', title: 'Gaius\' Hospitality' },
    ],
  },
  {
    id: 40,
    plan_type: 'jude',
    title: 'Jude - Contend for Faith',
    description: 'Defend the true faith',
    category: 'General Epistles',
    total_days: 1,
    icon: 'shield',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Jude', chapter: 1, verses: '1-25', title: 'Contend for the Faith' },
    ],
  },

  // ===== REVELATION (5 plans) =====
  {
    id: 41,
    plan_type: 'revelation_complete',
    title: 'Revelation - Complete',
    description: 'The unveiling of Jesus Christ',
    category: 'Prophecy',
    total_days: 22,
    icon: 'eye',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 22 }, (_, i) => ({
      book: 'Revelation',
      chapter: i + 1,
      verses: '1-21',
      title: `Revelation ${i + 1}`
    })),
  },
  {
    id: 42,
    plan_type: 'seven_churches',
    title: 'Seven Churches',
    description: 'Letters to the churches',
    category: 'Prophecy',
    total_days: 7,
    icon: 'home',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Revelation', chapter: 2, verses: '1-7', title: 'Ephesus' },
      { book: 'Revelation', chapter: 2, verses: '8-11', title: 'Smyrna' },
      { book: 'Revelation', chapter: 2, verses: '12-17', title: 'Pergamum' },
      { book: 'Revelation', chapter: 2, verses: '18-29', title: 'Thyatira' },
      { book: 'Revelation', chapter: 3, verses: '1-6', title: 'Sardis' },
      { book: 'Revelation', chapter: 3, verses: '7-13', title: 'Philadelphia' },
      { book: 'Revelation', chapter: 3, verses: '14-22', title: 'Laodicea' },
    ],
  },

  // ===== MAJOR PROPHETS (15 plans) =====
  {
    id: 43,
    plan_type: 'isaiah_messiah',
    title: 'Isaiah - The Messiah',
    description: 'Prophecies of Christ',
    category: 'Major Prophets',
    total_days: 30,
    icon: 'star',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Isaiah', chapter: 1, verses: '1-31', title: 'Rebellious Nation' },
      { book: 'Isaiah', chapter: 6, verses: '1-13', title: 'Isaiah\'s Call' },
      { book: 'Isaiah', chapter: 7, verses: '14', title: 'Immanuel' },
      { book: 'Isaiah', chapter: 9, verses: '1-7', title: 'Unto Us a Child' },
      { book: 'Isaiah', chapter: 11, verses: '1-10', title: 'Branch from Jesse' },
      { book: 'Isaiah', chapter: 25, verses: '1-12', title: 'Swallow Up Death' },
      { book: 'Isaiah', chapter: 26, verses: '1-21', title: 'Perfect Peace' },
      { book: 'Isaiah', chapter: 35, verses: '1-10', title: 'Desert Will Rejoice' },
      { book: 'Isaiah', chapter: 40, verses: '1-31', title: 'Comfort My People' },
      { book: 'Isaiah', chapter: 41, verses: '10-13', title: 'Fear Not' },
      { book: 'Isaiah', chapter: 42, verses: '1-9', title: 'My Servant' },
      { book: 'Isaiah', chapter: 43, verses: '1-7', title: 'You Are Mine' },
      { book: 'Isaiah', chapter: 44, verses: '1-8', title: 'Pour Out My Spirit' },
      { book: 'Isaiah', chapter: 45, verses: '22-25', title: 'Turn to Me' },
      { book: 'Isaiah', chapter: 49, verses: '1-13', title: 'Light to Nations' },
      { book: 'Isaiah', chapter: 50, verses: '4-11', title: 'Sustaining Word' },
      { book: 'Isaiah', chapter: 52, verses: '13-15', title: 'My Servant' },
      { book: 'Isaiah', chapter: 53, verses: '1-12', title: 'Suffering Servant' },
      { book: 'Isaiah', chapter: 54, verses: '1-17', title: 'Your Maker' },
      { book: 'Isaiah', chapter: 55, verses: '1-13', title: 'Come to the Waters' },
      { book: 'Isaiah', chapter: 58, verses: '6-14', title: 'True Fasting' },
      { book: 'Isaiah', chapter: 59, verses: '15-21', title: 'The Redeemer' },
      { book: 'Isaiah', chapter: 60, verses: '1-22', title: 'Arise, Shine' },
      { book: 'Isaiah', chapter: 61, verses: '1-11', title: 'Good News' },
      { book: 'Isaiah', chapter: 62, verses: '1-12', title: 'New Name' },
      { book: 'Isaiah', chapter: 63, verses: '7-19', title: 'Deeds of the Lord' },
      { book: 'Isaiah', chapter: 64, verses: '1-12', title: 'Rend the Heavens' },
      { book: 'Isaiah', chapter: 65, verses: '17-25', title: 'New Heavens' },
      { book: 'Isaiah', chapter: 66, verses: '1-24', title: 'Heaven is My Throne' },
      { book: 'Matthew', chapter: 1, verses: '22-23', title: 'Fulfilled in Christ' },
    ],
  },
  {
    id: 44,
    plan_type: 'jeremiah_weeping_prophet',
    title: 'Jeremiah - The Call',
    description: 'Called to the nations',
    category: 'Major Prophets',
    total_days: 20,
    icon: 'heart-dislike',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Jeremiah', chapter: 1, verses: '1-19', title: 'Jeremiah\'s Call' },
      { book: 'Jeremiah', chapter: 2, verses: '1-37', title: 'Forsaken the Lord' },
      { book: 'Jeremiah', chapter: 7, verses: '1-34', title: 'False Trust' },
      { book: 'Jeremiah', chapter: 15, verses: '10-21', title: 'Jeremiah\'s Complaint' },
      { book: 'Jeremiah', chapter: 17, verses: '5-10', title: 'Trust in the Lord' },
      { book: 'Jeremiah', chapter: 18, verses: '1-17', title: 'Potter\'s House' },
      { book: 'Jeremiah', chapter: 20, verses: '7-18', title: 'Fire in My Bones' },
      { book: 'Jeremiah', chapter: 23, verses: '1-8', title: 'Righteous Branch' },
      { book: 'Jeremiah', chapter: 29, verses: '1-14', title: 'Plans to Prosper' },
      { book: 'Jeremiah', chapter: 30, verses: '1-24', title: 'Restoration' },
      { book: 'Jeremiah', chapter: 31, verses: '1-40', title: 'New Covenant' },
      { book: 'Jeremiah', chapter: 32, verses: '1-44', title: 'Buy the Field' },
      { book: 'Jeremiah', chapter: 33, verses: '1-26', title: 'Call to Me' },
      { book: 'Lamentations', chapter: 3, verses: '19-26', title: 'Great is Thy Faithfulness' },
      { book: 'Lamentations', chapter: 3, verses: '55-66', title: 'Called on Your Name' },
      { book: 'Hebrews', chapter: 8, verses: '6-13', title: 'Better Covenant' },
      { book: 'Hebrews', chapter: 10, verses: '15-18', title: 'Remembered No More' },
      { book: '2 Corinthians', chapter: 3, verses: '1-18', title: 'New Covenant Ministers' },
      { book: 'Jeremiah', chapter: 9, verses: '23-24', title: 'Know the Lord' },
      { book: 'Jeremiah', chapter: 15, verses: '16', title: 'Your Words Were Found' },
    ],
  },
  {
    id: 45,
    plan_type: 'ezekiel_visions',
    title: 'Ezekiel - Visions',
    description: 'Prophetic visions and hope',
    category: 'Major Prophets',
    total_days: 15,
    icon: 'eye',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Ezekiel', chapter: 1, verses: '1-28', title: 'Throne Vision' },
      { book: 'Ezekiel', chapter: 2, verses: '1-10', title: 'Call to Prophesy' },
      { book: 'Ezekiel', chapter: 3, verses: '16-27', title: 'Watchman' },
      { book: 'Ezekiel', chapter: 10, verses: '1-22', title: 'Glory Departs' },
      { book: 'Ezekiel', chapter: 11, verses: '14-25', title: 'Promise of Return' },
      { book: 'Ezekiel', chapter: 18, verses: '1-32', title: 'Soul Who Sins' },
      { book: 'Ezekiel', chapter: 33, verses: '1-20', title: 'Watchman Again' },
      { book: 'Ezekiel', chapter: 34, verses: '1-31', title: 'Shepherds of Israel' },
      { book: 'Ezekiel', chapter: 36, verses: '22-38', title: 'New Heart' },
      { book: 'Ezekiel', chapter: 37, verses: '1-14', title: 'Dry Bones' },
      { book: 'Ezekiel', chapter: 37, verses: '15-28', title: 'One Nation' },
      { book: 'Ezekiel', chapter: 43, verses: '1-12', title: 'Glory Returns' },
      { book: 'Ezekiel', chapter: 47, verses: '1-12', title: 'River from Temple' },
      { book: 'John', chapter: 10, verses: '1-18', title: 'Good Shepherd' },
      { book: 'Revelation', chapter: 21, verses: '1-27', title: 'New Jerusalem' },
    ],
  },
  {
    id: 46,
    plan_type: 'daniel_faith',
    title: 'Daniel - Faithful in Exile',
    description: 'Standing firm in foreign land',
    category: 'Major Prophets',
    total_days: 12,
    icon: 'shield',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 12 }, (_, i) => ({
      book: 'Daniel',
      chapter: i + 1,
      verses: '1-49',
      title: `Daniel ${i + 1}`
    })),
  },

  // ===== MINOR PROPHETS (30+ plans) =====
  {
    id: 47,
    plan_type: 'hosea_unfailing_love',
    title: 'Hosea - Unfailing Love',
    description: 'God\'s faithful love',
    category: 'Minor Prophets',
    total_days: 14,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: Array.from({ length: 14 }, (_, i) => ({
      book: 'Hosea',
      chapter: i + 1,
      verses: '1-23',
      title: `Hosea ${i + 1}`
    })),
  },
  {
    id: 48,
    plan_type: 'joel_day_of_lord',
    title: 'Joel - Day of the Lord',
    description: 'Pour out My Spirit',
    category: 'Minor Prophets',
    total_days: 3,
    icon: 'flame',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: 'Joel',
      chapter: i + 1,
      verses: '1-32',
      title: `Joel ${i + 1}`
    })),
  },
  {
    id: 49,
    plan_type: 'amos_justice',
    title: 'Amos - Let Justice Roll',
    description: 'Call for justice and righteousness',
    category: 'Minor Prophets',
    total_days: 9,
    icon: 'scale',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 9 }, (_, i) => ({
      book: 'Amos',
      chapter: i + 1,
      verses: '1-27',
      title: `Amos ${i + 1}`
    })),
  },
  {
    id: 50,
    plan_type: 'obadiah',
    title: 'Obadiah - God\'s Justice',
    description: 'The day of the Lord is near',
    category: 'Minor Prophets',
    total_days: 1,
    icon: 'time',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Obadiah', chapter: 1, verses: '1-21', title: 'Kingdom is the Lord\'s' },
    ],
  },
  {
    id: 51,
    plan_type: 'jonah_reluctant',
    title: 'Jonah - Reluctant Prophet',
    description: 'Running from God',
    category: 'Minor Prophets',
    total_days: 4,
    icon: 'boat',
    color: theme.colors.secondary.sageGreen,
    verses: Array.from({ length: 4 }, (_, i) => ({
      book: 'Jonah',
      chapter: i + 1,
      verses: '1-17',
      title: `Jonah ${i + 1}`
    })),
  },
  {
    id: 52,
    plan_type: 'micah',
    title: 'Micah - What Does Lord Require',
    description: 'Act justly, love mercy',
    category: 'Minor Prophets',
    total_days: 7,
    icon: 'heart',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 7 }, (_, i) => ({
      book: 'Micah',
      chapter: i + 1,
      verses: '1-20',
      title: `Micah ${i + 1}`
    })),
  },
  {
    id: 53,
    plan_type: 'nahum',
    title: 'Nahum - God\'s Judgment',
    description: 'The Lord is good',
    category: 'Minor Prophets',
    total_days: 3,
    icon: 'shield',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: 'Nahum',
      chapter: i + 1,
      verses: '1-15',
      title: `Nahum ${i + 1}`
    })),
  },
  {
    id: 54,
    plan_type: 'habakkuk_faith',
    title: 'Habakkuk - Live by Faith',
    description: 'The righteous will live by faith',
    category: 'Minor Prophets',
    total_days: 3,
    icon: 'star',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: 'Habakkuk',
      chapter: i + 1,
      verses: '1-19',
      title: `Habakkuk ${i + 1}`
    })),
  },
  {
    id: 55,
    plan_type: 'zephaniah',
    title: 'Zephaniah - The Great Day',
    description: 'Seek the Lord',
    category: 'Minor Prophets',
    total_days: 3,
    icon: 'search',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 3 }, (_, i) => ({
      book: 'Zephaniah',
      chapter: i + 1,
      verses: '1-20',
      title: `Zephaniah ${i + 1}`
    })),
  },
  {
    id: 56,
    plan_type: 'haggai_rebuild',
    title: 'Haggai - Rebuild the Temple',
    description: 'Be strong and work',
    category: 'Minor Prophets',
    total_days: 2,
    icon: 'construct',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 2 }, (_, i) => ({
      book: 'Haggai',
      chapter: i + 1,
      verses: '1-23',
      title: `Haggai ${i + 1}`
    })),
  },
  {
    id: 57,
    plan_type: 'zechariah_visions',
    title: 'Zechariah - Night Visions',
    description: 'Not by might nor by power',
    category: 'Minor Prophets',
    total_days: 14,
    icon: 'eye',
    color: theme.colors.primary.royalBlue,
    verses: Array.from({ length: 14 }, (_, i) => ({
      book: 'Zechariah',
      chapter: i + 1,
      verses: '1-21',
      title: `Zechariah ${i + 1}`
    })),
  },
  {
    id: 58,
    plan_type: 'malachi_messenger',
    title: 'Malachi - The Messenger',
    description: 'The sun of righteousness',
    category: 'Minor Prophets',
    total_days: 4,
    icon: 'sunny',
    color: theme.colors.primary.warmGold,
    verses: Array.from({ length: 4 }, (_, i) => ({
      book: 'Malachi',
      chapter: i + 1,
      verses: '1-18',
      title: `Malachi ${i + 1}`
    })),
  },

  // ===== TOPICAL - LIFE ISSUES (30 plans) =====
  {
    id: 59,
    plan_type: 'dealing_with_fear',
    title: 'Overcoming Fear',
    description: 'God has not given us a spirit of fear',
    category: 'Life Issues',
    total_days: 7,
    icon: 'shield',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: '2 Timothy', chapter: 1, verses: '7', title: 'Spirit of Power' },
      { book: 'Isaiah', chapter: 41, verses: '10', title: 'Fear Not' },
      { book: 'Psalm', chapter: 27, verses: '1-3', title: 'Whom Shall I Fear' },
      { book: 'Psalm', chapter: 56, verses: '3-4', title: 'When I Am Afraid' },
      { book: '1 John', chapter: 4, verses: '18', title: 'Perfect Love Casts Out Fear' },
      { book: 'Joshua', chapter: 1, verses: '9', title: 'Be Strong and Courageous' },
      { book: 'Proverbs', chapter: 29, verses: '25', title: 'Fear of Man' },
    ],
  },
  {
    id: 60,
    plan_type: 'financial_wisdom',
    title: 'Biblical Money Management',
    description: 'Stewardship and generosity',
    category: 'Life Issues',
    total_days: 10,
    icon: 'cash',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Malachi', chapter: 3, verses: '8-12', title: 'Bring the Whole Tithe' },
      { book: 'Matthew', chapter: 6, verses: '19-24', title: 'Treasures in Heaven' },
      { book: 'Luke', chapter: 6, verses: '38', title: 'Give and It Will Be Given' },
      { book: '2 Corinthians', chapter: 9, verses: '6-15', title: 'Cheerful Giver' },
      { book: 'Proverbs', chapter: 3, verses: '9-10', title: 'Honor the Lord' },
      { book: 'Proverbs', chapter: 21, verses: '5', title: 'Plans of the Diligent' },
      { book: '1 Timothy', chapter: 6, verses: '6-10', title: 'Love of Money' },
      { book: 'Hebrews', chapter: 13, verses: '5-6', title: 'Content with What You Have' },
      { book: 'Philippians', chapter: 4, verses: '11-13', title: 'Content in All Situations' },
      { book: 'Proverbs', chapter: 13, verses: '11', title: 'Steady Plodding' },
    ],
  },
  {
    id: 61,
    plan_type: 'healing_comfort',
    title: 'Healing & Comfort',
    description: 'God heals the brokenhearted',
    category: 'Life Issues',
    total_days: 7,
    icon: 'heart',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Psalm', chapter: 147, verses: '3', title: 'Heals the Brokenhearted' },
      { book: 'Psalm', chapter: 34, verses: '18', title: 'Near to the Brokenhearted' },
      { book: '2 Corinthians', chapter: 1, verses: '3-7', title: 'God of All Comfort' },
      { book: 'Isaiah', chapter: 53, verses: '4-5', title: 'By His Wounds' },
      { book: 'Jeremiah', chapter: 17, verses: '14', title: 'Heal Me O Lord' },
      { book: 'James', chapter: 5, verses: '13-16', title: 'Prayer of Faith' },
      { book: 'Revelation', chapter: 21, verses: '4', title: 'Wipe Away Every Tear' },
    ],
  },
  {
    id: 62,
    plan_type: 'finding_purpose',
    title: 'Discovering God\'s Purpose',
    description: 'Why am I here?',
    category: 'Life Issues',
    total_days: 10,
    icon: 'compass',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: 'Jeremiah', chapter: 29, verses: '11', title: 'Plans to Prosper' },
      { book: 'Ephesians', chapter: 2, verses: '10', title: 'His Workmanship' },
      { book: 'Proverbs', chapter: 19, verses: '21', title: 'Lord\'s Purpose Prevails' },
      { book: 'Psalm', chapter: 139, verses: '13-16', title: 'Fearfully Made' },
      { book: 'Romans', chapter: 12, verses: '1-2', title: 'Living Sacrifice' },
      { book: 'Colossians', chapter: 3, verses: '23-24', title: 'Work as for the Lord' },
      { book: '1 Peter', chapter: 4, verses: '10-11', title: 'Use Your Gifts' },
      { book: 'Matthew', chapter: 28, verses: '19-20', title: 'Make Disciples' },
      { book: 'Philippians', chapter: 1, verses: '6', title: 'Complete the Work' },
      { book: 'Ecclesiastes', chapter: 12, verses: '13', title: 'Fear God' },
    ],
  },
  {
    id: 63,
    plan_type: 'marriage_family',
    title: 'Marriage & Family',
    description: 'Biblical perspective on family',
    category: 'Life Issues',
    total_days: 14,
    icon: 'people',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Genesis', chapter: 2, verses: '18-25', title: 'One Flesh' },
      { book: 'Ephesians', chapter: 5, verses: '22-33', title: 'Marriage Model' },
      { book: '1 Peter', chapter: 3, verses: '1-7', title: 'Respectful Partnership' },
      { book: 'Proverbs', chapter: 31, verses: '10-31', title: 'Noble Wife' },
      { book: 'Song of Solomon', chapter: 8, verses: '6-7', title: 'Love is Strong' },
      { book: 'Deuteronomy', chapter: 6, verses: '4-9', title: 'Teach Your Children' },
      { book: 'Proverbs', chapter: 22, verses: '6', title: 'Train Up a Child' },
      { book: 'Ephesians', chapter: 6, verses: '1-4', title: 'Children and Parents' },
      { book: 'Colossians', chapter: 3, verses: '18-21', title: 'Family Instructions' },
      { book: '1 Corinthians', chapter: 13, verses: '4-8', title: 'Love is Patient' },
      { book: 'Hebrews', chapter: 13, verses: '4', title: 'Honor Marriage' },
      { book: 'Psalm', chapter: 128, verses: '1-6', title: 'Blessed Family' },
      { book: 'Joshua', chapter: 24, verses: '15', title: 'Choose This Day' },
      { book: 'Malachi', chapter: 2, verses: '13-16', title: 'Guard Your Spirit' },
    ],
  },
  {
    id: 64,
    plan_type: 'work_career',
    title: 'Work & Career',
    description: 'Excellence in the workplace',
    category: 'Life Issues',
    total_days: 7,
    icon: 'briefcase',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Colossians', chapter: 3, verses: '23-24', title: 'Work as for the Lord' },
      { book: 'Proverbs', chapter: 16, verses: '3', title: 'Commit to the Lord' },
      { book: 'Proverbs', chapter: 22, verses: '29', title: 'Skilled Workers' },
      { book: 'Ephesians', chapter: 6, verses: '5-8', title: 'Serve with Sincerity' },
      { book: '1 Thessalonians', chapter: 4, verses: '11-12', title: 'Work with Your Hands' },
      { book: '2 Thessalonians', chapter: 3, verses: '10-13', title: 'Willing to Work' },
      { book: 'Proverbs', chapter: 14, verses: '23', title: 'Profit from Hard Work' },
    ],
  },
  {
    id: 65,
    plan_type: 'loneliness',
    title: 'Overcoming Loneliness',
    description: 'You are never alone',
    category: 'Life Issues',
    total_days: 7,
    icon: 'person',
    color: theme.colors.secondary.sageGreen,
    verses: [
      { book: 'Deuteronomy', chapter: 31, verses: '6', title: 'Never Leave You' },
      { book: 'Hebrews', chapter: 13, verses: '5-6', title: 'Never Forsake You' },
      { book: 'Psalm', chapter: 68, verses: '6', title: 'God Sets the Lonely' },
      { book: 'Psalm', chapter: 25, verses: '16-17', title: 'Turn to Me' },
      { book: 'Matthew', chapter: 28, verses: '20', title: 'With You Always' },
      { book: 'Isaiah', chapter: 41, verses: '10', title: 'I Am With You' },
      { book: 'John', chapter: 14, verses: '18', title: 'Not Leave You Orphaned' },
    ],
  },
  {
    id: 66,
    plan_type: 'temptation_sin',
    title: 'Resisting Temptation',
    description: 'Victory over sin',
    category: 'Life Issues',
    total_days: 10,
    icon: 'shield-checkmark',
    color: theme.colors.primary.royalBlue,
    verses: [
      { book: '1 Corinthians', chapter: 10, verses: '13', title: 'Way of Escape' },
      { book: 'James', chapter: 1, verses: '12-15', title: 'Crown of Life' },
      { book: 'James', chapter: 4, verses: '7', title: 'Resist the Devil' },
      { book: 'Hebrews', chapter: 4, verses: '15-16', title: 'Sympathetic High Priest' },
      { book: 'Hebrews', chapter: 2, verses: '18', title: 'Help the Tempted' },
      { book: 'Romans', chapter: 6, verses: '11-14', title: 'Dead to Sin' },
      { book: 'Galatians', chapter: 5, verses: '16-17', title: 'Walk by the Spirit' },
      { book: '1 John', chapter: 1, verses: '9', title: 'If We Confess' },
      { book: 'Psalm', chapter: 119, verses: '9-11', title: 'Hide Your Word' },
      { book: '2 Peter', chapter: 1, verses: '3-11', title: 'Escape Corruption' },
    ],
  },
  {
    id: 67,
    plan_type: 'grief_loss',
    title: 'Hope in Grief',
    description: 'Comfort in times of loss',
    category: 'Life Issues',
    total_days: 7,
    icon: 'heart-half',
    color: theme.colors.secondary.softPeach,
    verses: [
      { book: 'Psalm', chapter: 23, verses: '1-6', title: 'Valley of Shadow' },
      { book: 'Psalm', chapter: 34, verses: '18', title: 'Near the Brokenhearted' },
      { book: 'John', chapter: 14, verses: '1-4', title: 'Do Not Let Hearts Be Troubled' },
      { book: '1 Thessalonians', chapter: 4, verses: '13-18', title: 'Hope for Believers' },
      { book: '2 Corinthians', chapter: 1, verses: '3-7', title: 'God of Comfort' },
      { book: 'Revelation', chapter: 21, verses: '1-5', title: 'No More Death' },
      { book: 'Romans', chapter: 8, verses: '38-39', title: 'Nothing Can Separate' },
    ],
  },
  {
    id: 68,
    plan_type: 'decision_making',
    title: 'Making Wise Decisions',
    description: 'Seeking God\'s guidance',
    category: 'Life Issues',
    total_days: 7,
    icon: 'map',
    color: theme.colors.primary.warmGold,
    verses: [
      { book: 'Proverbs', chapter: 3, verses: '5-6', title: 'Trust in the Lord' },
      { book: 'James', chapter: 1, verses: '5-8', title: 'Ask for Wisdom' },
      { book: 'Psalm', chapter: 32, verses: '8', title: 'I Will Instruct You' },
      { book: 'Proverbs', chapter: 15, verses: '22', title: 'Plans Succeed' },
      { book: 'Isaiah', chapter: 30, verses: '21', title: 'This is the Way' },
      { book: 'Colossians', chapter: 3, verses: '15', title: 'Peace of Christ Rule' },
      { book: 'Romans', chapter: 12, verses: '2', title: 'Test and Approve' },
    ],
  },
];

// Total number of extended plans
export const TOTAL_EXTENDED_PLANS = EXTENDED_READING_PLANS.length;

